// GENERATED by scripts/build-design-scene.mjs from design/templates.
// Do not edit by hand — edit the template and re-run `npm run design:scene`.
/* eslint-disable @next/next/no-img-element */
import { Fragment, type CSSProperties } from "react";

// The scene leans on CSS custom properties for every animated value, so most
// declarations are var()/calc() strings that React's own CSSProperties types
// reject on principle. One cast at the boundary beats 1200 of them.
const s = (o: Record<string, string | number>) => o as CSSProperties;

export const SceneHomeMobileHover = ".jhmh0:hover{transform:translateY(-4px)}\n.jhmh1:hover{transform:translateX(4px)}\n.jhmh2:hover{background:#141311;color:#f4f1e6}\n.jhmh3:hover{transform:translateY(-3px)}\n.jhmh4:hover{transform:translateY(-3px)}\n.jhmh5:hover{transform:translateY(-3px)}\n.jhmh6:hover{transform:translateY(-3px)}\n.jhmh7:hover{transform:translateX(-50%) scale(1.06);background:#8ad183}";

export function SceneHomeMobile({ V }: { V: any }) {
  return (
    <>
      <style>{SceneHomeMobileHover}</style>
      <div style={s({ "height": "660vh", "position": "relative", "background": "#0f0e0c" })}>
        <div ref={V.refRoom} style={s({ "position": "sticky", "top": "0", "height": "100vh", "overflow": "hidden", "perspective": "1900px", "perspectiveOrigin": "50% 46%", "background": "radial-gradient(132% 122% at 50% 36%,#26263d 0%,#15141f 44%,#0a0910 76%,#060509 100%)" })}>
          <div style={s({ "position": "absolute", "inset": "0", "background": "radial-gradient(46% 54% at 50% 44%,rgba(120,150,210,.24) 0%,rgba(13,11,20,0) 72%)", "pointerEvents": "none" })}></div>
          <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "0", "height": "38%", "background": "linear-gradient(180deg,rgba(4,3,8,0) 0%,rgba(4,3,8,.5) 62%,rgba(4,3,8,.84) 100%)", "pointerEvents": "none" })}></div>
          <div style={s({ "position": "absolute", "left": "50%", "top": "50%", "width": "462px", "height": "964px", "transform": "translate(-50%,-50%) scale(var(--fit,1)) rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg))", "transformStyle": "preserve-3d", "willChange": "transform" })}>
            <div style={s({ "position": "absolute", "left": "6%", "right": "6%", "bottom": "-46px", "height": "104px", "background": "radial-gradient(ellipse at center,rgba(0,0,0,.72) 0%,rgba(0,0,0,0) 72%)", "filter": "blur(3px)" })}></div>
            <div style={s({ "position": "relative", "width": "462px", "height": "964px", "boxSizing": "border-box", "padding": "16px", "borderRadius": "68px", "background": "linear-gradient(158deg,#615c52 0%,#332f2a 24%,#1a1815 60%,#0d0c0a 100%)", "boxShadow": "inset 0 3px 0 rgba(255,255,255,.36),inset 3px 0 0 rgba(255,255,255,.16),inset -3px 0 0 rgba(0,0,0,.55),inset 0 -6px 0 rgba(0,0,0,.65),0 8px 0 #0a0908,0 24px 30px rgba(4,3,8,.55),0 66px 86px rgba(4,3,8,.62),0 124px 150px rgba(4,3,8,.5)" })}>
              <div style={s({ "position": "absolute", "left": "-4px", "top": "216px", "width": "5px", "height": "36px", "borderRadius": "4px 0 0 4px", "background": "linear-gradient(90deg,#6f6a60,#2a2823)" })}></div>
              <div style={s({ "position": "absolute", "left": "-4px", "top": "276px", "width": "5px", "height": "64px", "borderRadius": "4px 0 0 4px", "background": "linear-gradient(90deg,#6f6a60,#2a2823)" })}></div>
              <div style={s({ "position": "absolute", "left": "-4px", "top": "354px", "width": "5px", "height": "64px", "borderRadius": "4px 0 0 4px", "background": "linear-gradient(90deg,#6f6a60,#2a2823)" })}></div>
              <div style={s({ "position": "absolute", "right": "-4px", "top": "302px", "width": "5px", "height": "106px", "borderRadius": "0 4px 4px 0", "background": "linear-gradient(270deg,#6f6a60,#2a2823)" })}></div>
              <div style={s({ "position": "relative", "width": "430px", "height": "932px", "borderRadius": "52px", "overflow": "hidden", "background": "#0f0e0c", "boxShadow": "inset 0 0 0 2px #000" })} className="jos-crt">
                <div className="jos-scanline"></div>
                <div style={s({ "position": "absolute", "inset": "0", "background": "linear-gradient(var(--sky-top,#0b0d0b) 0%,var(--sky-mid,#121a13) 46%,var(--sky-bot,#1f2e20) 100%)", "transition": "background 1.1s ease" })}></div>
                <div style={s({ "position": "absolute", "inset": "0", "background": "radial-gradient(74% 32% at 50% 84%,var(--glow,#7ac274) 0%,rgba(0,0,0,0) 70%)", "opacity": ".18", "transition": "background 1.1s ease", "pointerEvents": "none" })}></div>
                <div style={s({ "position": "absolute", "inset": "0", "opacity": ".9", "pointerEvents": "none" })}>
                  <div style={s({ "position": "absolute", "left": "12%", "top": "9%", "width": "3px", "height": "3px", "background": "#fff", "animation": "twinkle 3s ease-in-out infinite" })}></div>
                  <div style={s({ "position": "absolute", "left": "31%", "top": "14%", "width": "3px", "height": "3px", "background": "#fff", "animation": "twinkle 4.5s ease-in-out infinite" })}></div>
                  <div style={s({ "position": "absolute", "left": "58%", "top": "8%", "width": "3px", "height": "3px", "background": "#fff", "animation": "twinkle 3.8s ease-in-out infinite" })}></div>
                  <div style={s({ "position": "absolute", "left": "78%", "top": "13%", "width": "3px", "height": "3px", "background": "#fff", "animation": "twinkle 5.2s ease-in-out infinite" })}></div>
                  <div style={s({ "position": "absolute", "left": "46%", "top": "20%", "width": "3px", "height": "3px", "background": "#fff", "animation": "twinkle 4.1s ease-in-out infinite" })}></div>
                </div>
                <div style={s({ "position": "absolute", "left": "8%", "top": "15%", "animation": "drift 22s ease-in-out infinite alternate", "opacity": ".13", "pointerEvents": "none" })}>
                  <div style={s({ "width": "96px", "height": "13px", "background": "#8d887d" })}></div>
                  <div style={s({ "width": "56px", "height": "14px", "background": "#fff", "position": "absolute", "left": "20px", "top": "-14px" })}></div>
                </div>
                <div style={s({ "position": "absolute", "left": "-4%", "right": "-4%", "bottom": "150px", "height": "210px", "transform": "translateX(calc(var(--p,0) * -38px))", "pointerEvents": "none" })}>
                  <div style={s({ "position": "absolute", "left": "2%", "bottom": "0", "width": "44px", "height": "104px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-far,#1a231b) 0 10px,transparent 10px 16px),repeating-linear-gradient(90deg,rgba(255,233,168,.5) 0 5px,transparent 5px 13px)" })}></div>
                  <div style={s({ "position": "absolute", "left": "13%", "bottom": "0", "width": "34px", "height": "76px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                  <div style={s({ "position": "absolute", "left": "22%", "bottom": "0", "width": "56px", "height": "150px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-far,#1a231b) 0 10px,transparent 10px 16px),repeating-linear-gradient(90deg,rgba(255,233,168,.5) 0 5px,transparent 5px 13px)" })}></div>
                  <div style={s({ "position": "absolute", "left": "38%", "bottom": "0", "width": "46px", "height": "186px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "clipPath": "polygon(44% 0,56% 0,100% 100%,0 100%)" })}></div>
                  <div style={s({ "position": "absolute", "left": "52%", "bottom": "0", "width": "40px", "height": "112px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                  <div style={s({ "position": "absolute", "left": "64%", "bottom": "0", "width": "58px", "height": "158px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-far,#1a231b) 0 10px,transparent 10px 16px),repeating-linear-gradient(90deg,rgba(255,233,168,.5) 0 5px,transparent 5px 13px)" })}></div>
                  <div style={s({ "position": "absolute", "left": "80%", "bottom": "0", "width": "38px", "height": "126px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                  <div style={s({ "position": "absolute", "left": "90%", "bottom": "0", "width": "52px", "height": "92px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                </div>
                <div style={s({ "position": "absolute", "left": "-3%", "right": "-3%", "bottom": "150px", "height": "240px", "transform": "translateX(calc(var(--p,0) * -84px))", "pointerEvents": "none" })}>
                  <div style={s({ "position": "absolute", "left": "0%", "bottom": "0", "width": "42px", "height": "70px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-near,#0f1411) 0 10px,transparent 10px 15px),repeating-linear-gradient(90deg,rgba(255,233,168,.9) 0 6px,transparent 6px 13px)" })}></div>
                  <div style={s({ "position": "absolute", "left": "11%", "bottom": "0", "width": "66px", "height": "84px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                  <div style={s({ "position": "absolute", "left": "11%", "bottom": "84px", "width": "66px", "height": "38px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(0 100%,0 62%,12% 62%,12% 38%,30% 38%,30% 16%,44% 16%,44% 4%,56% 4%,56% 16%,70% 16%,70% 38%,88% 38%,88% 62%,100% 62%,100% 100%)" })}></div>
                  <div style={s({ "position": "absolute", "left": "32%", "bottom": "0", "width": "44px", "height": "172px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                  <div style={s({ "position": "absolute", "left": "33%", "bottom": "132px", "width": "28px", "height": "28px", "background": "#ffe9a8", "opacity": ".9" })}></div>
                  <div style={s({ "position": "absolute", "left": "34%", "bottom": "138px", "width": "16px", "height": "16px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                  <div style={s({ "position": "absolute", "left": "32%", "bottom": "172px", "width": "44px", "height": "40px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(42% 0,58% 0,58% 24%,72% 24%,72% 52%,86% 52%,86% 78%,100% 78%,100% 100%,0 100%,0 78%,14% 78%,14% 52%,28% 52%,28% 24%,42% 24%)" })}></div>
                  <div style={s({ "position": "absolute", "left": "52%", "bottom": "0", "width": "150px", "height": "112px" })}>
                    <div style={s({ "position": "absolute", "left": "0", "bottom": "0", "width": "24px", "height": "92px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "right": "0", "bottom": "0", "width": "24px", "height": "92px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "0", "bottom": "16px", "width": "150px", "height": "9px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "24px", "bottom": "25px", "width": "102px", "height": "46px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(0 100%,0 46%,12% 46%,12% 24%,28% 24%,28% 8%,44% 8%,44% 0,56% 0,56% 8%,72% 8%,72% 24%,88% 24%,88% 46%,100% 46%,100% 100%,88% 100%,88% 62%,72% 62%,72% 40%,56% 40%,56% 26%,44% 26%,44% 40%,28% 40%,28% 62%,12% 62%,12% 100%)" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "84%", "bottom": "0", "width": "48px", "height": "120px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-near,#0f1411) 0 10px,transparent 10px 15px),repeating-linear-gradient(90deg,rgba(255,233,168,.9) 0 6px,transparent 6px 13px)" })}></div>
                  <div style={s({ "position": "absolute", "left": "95%", "bottom": "0", "width": "40px", "height": "78px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                </div>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "78px", "height": "72px", "background": "var(--river,#0c1210)", "pointerEvents": "none" })}></div>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "118px", "height": "6px", "background": "var(--river-lit,#2b4130)", "opacity": ".7", "pointerEvents": "none" })}></div>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "96px", "height": "4px", "background": "var(--river-lit,#2b4130)", "opacity": ".45", "pointerEvents": "none" })}></div>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "146px", "height": "8px", "background": "var(--embank,#0a0e0b)", "pointerEvents": "none" })}></div>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "0", "height": "78px", "background": "var(--fore,#080b09)", "pointerEvents": "none" })}></div>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "72px", "height": "7px", "background": "var(--fore-lit,#131a14)", "pointerEvents": "none" })}></div>
                <div style={s({ "position": "absolute", "left": "16px", "top": "78px", "width": "398px", "zIndex": "10", "pointerEvents": "var(--pe0,auto)", "transformOrigin": "199px 860px", "opacity": "calc(1 - clamp(0, (var(--p,0) - .2) * 14, 1))", "transform": "scale(calc(1.03 - 1.0 * clamp(0, (var(--p,0) - .2) * 14, 1)))" })} className="jos-z0">
                  <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "11px 12px 0 #141311,0 30px 60px -22px rgba(4,3,8,.7)" })}>
                    <div style={s({ "height": "46px", "display": "flex", "alignItems": "center", "gap": "12px", "padding": "0 16px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                      <div style={s({ "width": "12px", "height": "12px", "borderRadius": "999px", "background": "#141311", "flex": "none" })}></div>
                      <span style={s({ "fontSize": "16px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                        {"Me"}
                      </span>
                      <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#6f6a61", "marginLeft": "auto" })}>
                        {"1 of 4"}
                      </span>
                    </div>
                    <div style={s({ "padding": "16px 20px 20px", "display": "flex", "flexDirection": "column", "gap": "13px" })}>
                      <div style={s({ "display": "flex", "alignItems": "center", "gap": "10px" })}>
                        <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".16em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                          {"Personal site, 2026"}
                        </span>
                        <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                        <div style={s({ "width": "9px", "height": "9px", "borderRadius": "999px", "background": "#7ac274" })}></div>
                      </div>
                      <div style={s({ "alignSelf": "center", "width": "150px", "height": "150px", "borderRadius": "999px", "overflow": "hidden", "background": "#e6e1d3", "boxShadow": "7px 8px 0 #141311" })}>
                        <img src="/assets/portrait.png" alt="Jawad Jalal" style={s({ "width": "100%", "height": "100%", "objectFit": "cover", "display": "block" })} />
                      </div>
                      <div style={s({ "display": "flex", "flexDirection": "column" })}>
                        <span style={s({ "fontSize": "62px", "fontWeight": "700", "letterSpacing": "-.06em", "lineHeight": ".86", "color": "#141311", "animation": "hit .52s cubic-bezier(.34,1.56,.64,1) both" })}>
                          {"JAWAD"}
                        </span>
                        <span style={s({ "fontSize": "62px", "fontWeight": "700", "letterSpacing": "-.06em", "lineHeight": ".86", "color": "#141311", "animation": "hit .52s .09s cubic-bezier(.34,1.56,.64,1) both" })}>
                          {"JALAL"}
                        </span>
                      </div>
                      <span style={s({ "fontSize": "21px", "fontWeight": "600", "letterSpacing": "-.03em", "lineHeight": "1.15", "color": "#5c5850", "animation": "rise .45s .2s ease-out both" })}>
                        {"Designer and Founder. Building the good‑looking."}
                      </span>
                      <p style={s({ "margin": "0", "fontSize": "16px", "lineHeight": "1.45", "color": "#3a3630", "textWrap": "pretty", "animation": "rise .5s .28s ease-out both" })}>
                        {V.bio}
                      </p>
                      <div onClick={V.jWork} style={s({ "display": "flex", "alignItems": "center", "gap": "12px", "background": "#7ac274", "borderRadius": "20px", "padding": "15px 15px 15px 19px", "boxShadow": "6px 7px 0 #141311", "cursor": "pointer", "animation": "rise .5s .34s ease-out both" })}>
                        <div style={s({ "display": "flex", "flexDirection": "column", "gap": "2px" })}>
                          <span style={s({ "fontSize": "24px", "fontWeight": "700", "letterSpacing": "-.035em", "lineHeight": "1", "color": "#12300f" })}>
                            {"What I have built"}
                          </span>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#1d3d1c" })}>
                            {V.builtLine}
                          </span>
                        </div>
                        <div style={s({ "position": "relative", "width": "40px", "height": "40px", "borderRadius": "999px", "background": "#141311", "flex": "none", "marginLeft": "auto" })}>
                          <div style={s({ "position": "absolute", "left": "14px", "top": "12px", "width": "11px", "height": "2.5px", "background": "#f4f1e6", "transform": "rotate(45deg)", "transformOrigin": "left center" })}></div>
                          <div style={s({ "position": "absolute", "left": "14px", "top": "28px", "width": "11px", "height": "2.5px", "background": "#f4f1e6", "transform": "rotate(-45deg)", "transformOrigin": "left center" })}></div>
                        </div>
                      </div>
                      <a href={V.cvHref} download={V.cvFilename} style={s({ "display": "flex", "alignItems": "center", "gap": "12px", "borderRadius": "18px", "padding": "13px 13px 13px 17px", "boxShadow": "inset 0 0 0 2.5px #141311", "animation": "rise .5s .4s ease-out both" })}>
                        <span style={s({ "fontSize": "18px", "fontWeight": "700", "letterSpacing": "-.02em", "color": "#141311" })}>
                          {"Download CV"}
                        </span>
                        <span style={s({ "width": "32px", "height": "32px", "borderRadius": "999px", "background": "#141311", "color": "#f4f1e6", "fontSize": "16px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none", "marginLeft": "auto" })}>
                          {"↓"}
                        </span>
                      </a>
                    </div>
                    <div style={s({ "display": "flex", "alignItems": "center", "padding": "11px 18px", "boxShadow": "inset 0 2.5px 0 #141311" })}>
                      <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#5c5850" })}>
                        {"Scroll to open the rest"}
                      </span>
                    </div>
                  </div>
                </div>
                <div style={s({ "position": "absolute", "left": "16px", "top": "78px", "width": "398px", "zIndex": "11", "pointerEvents": "var(--pe1,none)", "transformOrigin": "199px 860px", "opacity": "calc(clamp(0, (var(--p,0) - .21) * 14, 1) - clamp(0, (var(--p,0) - .45) * 14, 1))", "transform": "scale(calc(.04 + 1.02 * clamp(0, (var(--p,0) - .21) * 14, 1) - 1.02 * clamp(0, (var(--p,0) - .45) * 14, 1)))" })} className="jos-z1">
                  <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "11px 12px 0 #141311,0 30px 60px -22px rgba(4,3,8,.7)" })}>
                    <div style={s({ "height": "46px", "display": "flex", "alignItems": "center", "gap": "12px", "padding": "0 16px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                      <div style={s({ "width": "12px", "height": "12px", "borderRadius": "999px", "background": "#141311", "flex": "none" })}></div>
                      <span style={s({ "fontSize": "16px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                        {"Experience"}
                      </span>
                      <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#6f6a61", "marginLeft": "auto" })}>
                        {"2 of 4"}
                      </span>
                    </div>
                    <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "10px", "padding": "16px 20px 10px" })}>
                      <span style={s({ "fontSize": "30px", "fontWeight": "700", "letterSpacing": "-.04em", "color": "#141311" })} className="jos-zw">
                        {"Things I started"}
                      </span>
                      <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850", "marginLeft": "auto" })}>
                        {V.ventureCount}
                      </span>
                    </div>
                    <div style={s({ "height": "520px", "overflow": "hidden", "position": "relative" })}>
                      <div style={s({ "display": "flex", "flexDirection": "column", "gap": "16px", "padding": "2px 20px 0", "transform": "translateY(calc(-1 * clamp(0px, (var(--p,0) - .26) * 9200px, 1580px)))" })}>
                        {(V.ventures ?? []).map((v: any, vIndex: number) => (
                          <Fragment key={vIndex}>
                            <a href={v.href} target="_blank" rel="noreferrer" style={s({ "display": "flex", "flexDirection": "column", "gap": "8px", "transition": "transform .2s cubic-bezier(.2,.9,.3,1)" })} className="jhmh0">
                              <div style={s({ "height": "158px", "borderRadius": "14px", "overflow": "hidden", "background": "#e6e1d3", "boxShadow": "5px 6px 0 #141311" })}>
                                <img src={v.shot} alt={v.name} style={s({ "width": "100%", "height": "100%", "objectFit": "cover", "objectPosition": "50% 8%", "display": "block" })} />
                              </div>
                              <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "10px" })}>
                                <span style={s({ "fontSize": "22px", "fontWeight": "700", "letterSpacing": "-.03em", "color": "#141311" })}>
                                  {v.name}
                                </span>
                                <span style={s({ "fontSize": "11px", "fontWeight": "700", "letterSpacing": ".12em", "textTransform": "uppercase", "color": "#12300f", "background": "#7ac274", "borderRadius": "999px", "padding": "4px 9px", "marginLeft": "auto" })}>
                                  {v.status}
                                </span>
                              </div>
                              <span style={s({ "fontSize": "16px", "lineHeight": "1.25", "color": "#3a3630" })}>
                                {v.tagline}
                              </span>
                              <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".12em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                                {v.role}
                              </span>
                            </a>
                          </Fragment>
                        ))}
                        <div style={s({ "display": "flex", "alignItems": "center", "gap": "10px", "paddingTop": "4px" })}>
                          <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                            {"Where I work"}
                          </span>
                          <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                          <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#6f6a61" })}>
                            {V.roleCount}
                          </span>
                        </div>
                        {(V.roles ?? []).map((role: any, roleIndex: number) => (
                          <Fragment key={roleIndex}>
                            <a href={role.url} target="_blank" rel="noreferrer" style={s({ "display": "flex", "flexDirection": "column", "gap": "3px", "transition": "transform .18s cubic-bezier(.2,.9,.3,1)" })} className="jhmh1">
                              <div style={s({ "display": "flex", "alignItems": "center", "gap": "9px" })}>
                                <img src={role.icon} alt="" style={s({ "width": "16px", "height": "16px", "flex": "none", "borderRadius": "4px", "objectFit": "contain", "display": "block" })} />
                                <span style={s({ "fontSize": "11px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                                  {role.year}
                                </span>
                              </div>
                              <span style={s({ "fontSize": "19px", "fontWeight": "700", "letterSpacing": "-.03em", "lineHeight": "1.1", "color": "#141311" })}>
                                {role.org}
                              </span>
                              <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                                {role.role}
                              </span>
                              <span style={s({ "fontSize": "14px", "lineHeight": "1.3", "color": "#3a3630", "display": "-webkit-box", "WebkitLineClamp": "2", "WebkitBoxOrient": "vertical", "overflow": "hidden" })}>
                                {role.detail}
                              </span>
                            </a>
                          </Fragment>
                        ))}
                        <div style={s({ "display": "flex", "alignItems": "center", "gap": "10px", "paddingTop": "4px" })}>
                          <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                            {"Sites for other people"}
                          </span>
                          <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                        </div>
                        {(V.webWork ?? []).map((w: any, wIndex: number) => (
                          <Fragment key={wIndex}>
                            <a href={w.href} target="_blank" rel="noreferrer" style={s({ "display": "flex", "flexDirection": "column", "gap": "2px" })}>
                              <span style={s({ "fontSize": "17px", "fontWeight": "700", "color": "#141311" })}>
                                {w.name}
                              </span>
                              <span style={s({ "fontSize": "14px", "color": "#6f6a61" })}>
                                {w.note}
                              </span>
                            </a>
                          </Fragment>
                        ))}
                      </div>
                      <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "0", "height": "44px", "background": "linear-gradient(180deg,rgba(244,241,230,0),#f4f1e6)", "pointerEvents": "none" })}></div>
                    </div>
                    <div style={s({ "padding": "10px 20px 14px" })}>
                      <div style={s({ "height": "8px", "borderRadius": "4px", "background": "#e6e1d3" })}>
                        <div style={s({ "height": "8px", "width": "42%", "borderRadius": "4px", "background": "#141311", "marginLeft": "calc(clamp(0, (var(--p,0) - .26) * 9200 / 1580, 1) * 58%)" })}></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div style={s({ "position": "absolute", "left": "16px", "top": "78px", "width": "398px", "zIndex": "12", "pointerEvents": "var(--pe2,none)", "transformOrigin": "199px 860px", "opacity": "calc(clamp(0, (var(--p,0) - .46) * 14, 1) - clamp(0, (var(--p,0) - .7) * 14, 1))", "transform": "scale(calc(.04 + 1.02 * clamp(0, (var(--p,0) - .46) * 14, 1) - 1.02 * clamp(0, (var(--p,0) - .7) * 14, 1)))" })} className="jos-z2">
                  <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "11px 12px 0 #141311,0 30px 60px -22px rgba(4,3,8,.7)" })}>
                    <div style={s({ "height": "46px", "display": "flex", "alignItems": "center", "gap": "12px", "padding": "0 16px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                      <div style={s({ "width": "12px", "height": "12px", "borderRadius": "999px", "background": "#141311", "flex": "none" })}></div>
                      <span style={s({ "fontSize": "16px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                        {"Writing"}
                      </span>
                      <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#6f6a61", "marginLeft": "auto" })}>
                        {"3 of 4"}
                      </span>
                    </div>
                    <div style={s({ "padding": "18px 20px 18px", "boxShadow": "inset 0 -2.5px 0 #141311", "display": "flex", "flexDirection": "column", "gap": "12px" })}>
                      <span style={s({ "fontSize": "40px", "fontWeight": "700", "letterSpacing": "-.045em", "lineHeight": "1", "color": "#141311" })} className="jos-zw">
                        {"Writing"}
                      </span>
                      <p style={s({ "margin": "0", "fontSize": "16px", "lineHeight": "1.45", "color": "#3a3630", "textWrap": "pretty" })}>
                        {" Notes on the things on this page: designing them, building them, and getting them out of the door. It all lives at /writing. "}
                      </p>
                      <a href="/writing" style={s({ "display": "flex", "alignItems": "center", "gap": "12px", "background": "#141311", "borderRadius": "18px", "padding": "14px 14px 14px 18px" })}>
                        <span style={s({ "fontSize": "20px", "fontWeight": "700", "letterSpacing": "-.03em", "color": "#f4f1e6" })}>
                          {"Read the writing"}
                        </span>
                        <span style={s({ "width": "34px", "height": "34px", "borderRadius": "999px", "background": "#7ac274", "color": "#12300f", "fontSize": "17px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none", "marginLeft": "auto" })}>
                          {"→"}
                        </span>
                      </a>
                    </div>
                    <div style={s({ "padding": "18px 20px 10px", "display": "flex", "flexDirection": "column", "gap": "8px" })}>
                      <span style={s({ "fontSize": "28px", "fontWeight": "700", "letterSpacing": "-.04em", "color": "#141311", "--zd": ".1s" })} className="jos-zr">
                        {"Newsletter"}
                      </span>
                      <span style={s({ "fontSize": "16px", "lineHeight": "1.4", "color": "#3a3630" })}>
                        {"One email when something ships. Your address, nothing else."}
                      </span>
                    </div>
                    <div style={s({ "display": "flex", "alignItems": "center", "gap": "14px", "padding": "0 20px", "boxShadow": "inset 0 -2.5px 0 #e6e1d3,inset 0 2.5px 0 #e6e1d3" })}>
                      <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#5c5850", "width": "52px", "flex": "none" })}>
                        {"Email"}
                      </span>
                      <input ref={V.refSub} onKeyDown={V.onSubKey} type="email" autoComplete="email" placeholder="you@somewhere.com" style={s({ "flex": "1", "minWidth": "0", "border": "none", "background": "transparent", "padding": "15px 0", "fontSize": "19px", "color": "#141311", "outline": "none", "caretColor": "#7ac274" })} />
                    </div>
                    <div style={s({ "padding": "16px 20px 4px", "display": "flex", "flexDirection": "column", "gap": "12px" })}>
                      <div onClick={V.subscribe} style={s({ "fontSize": "18px", "fontWeight": "700", "background": "#7ac274", "color": "#12300f", "borderRadius": "16px", "padding": "17px", "textAlign": "center", "cursor": "pointer", "boxShadow": "5px 6px 0 #141311" })}>
                        {V.subLabel}
                      </div>
                      {V.subOk ? (
                        <>
                          <div style={s({ "display": "flex", "alignItems": "center", "gap": "11px", "background": "#7ac274", "borderRadius": "14px", "padding": "13px 15px" })}>
                            <span style={s({ "width": "24px", "height": "24px", "borderRadius": "999px", "background": "#141311", "color": "#f4f1e6", "fontSize": "13px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none" })}>
                              {"✓"}
                            </span>
                            <span style={s({ "fontSize": "16px", "fontWeight": "600", "color": "#12300f" })}>
                              {"You are on the list."}
                            </span>
                          </div>
                        </>
                      ) : null}
                      {V.subErr ? (
                        <>
                          <div style={s({ "display": "flex", "alignItems": "center", "gap": "11px", "background": "#141311", "borderRadius": "14px", "padding": "13px 15px" })}>
                            <span style={s({ "width": "24px", "height": "24px", "borderRadius": "999px", "background": "#7ac274", "color": "#12300f", "fontSize": "14px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none" })}>
                              {"!"}
                            </span>
                            <span style={s({ "fontSize": "16px", "fontWeight": "600", "color": "#f4f1e6" })}>
                              {V.subError}
                            </span>
                          </div>
                        </>
                      ) : null}
                    </div>
                    <div style={s({ "display": "flex", "alignItems": "center", "padding": "12px 20px 16px" })}>
                      <span style={s({ "fontSize": "14px", "color": "#6f6a61" })}>
                        {"No schedule, no spam, unsubscribe whenever."}
                      </span>
                    </div>
                  </div>
                </div>
                <div style={s({ "position": "absolute", "left": "16px", "top": "78px", "width": "398px", "zIndex": "13", "pointerEvents": "var(--pe3,none)", "transformOrigin": "199px 860px", "opacity": "clamp(0, calc((var(--p,0) - .71) * 14), 1)", "transform": "scale(calc(.04 + 1.02 * clamp(0, (var(--p,0) - .71) * 14, 1)))" })} className="jos-z3">
                  <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "11px 12px 0 #141311,0 30px 60px -22px rgba(4,3,8,.7)" })}>
                    <div style={s({ "height": "46px", "display": "flex", "alignItems": "center", "gap": "12px", "padding": "0 16px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                      <div style={s({ "width": "12px", "height": "12px", "borderRadius": "999px", "background": "#141311", "flex": "none" })}></div>
                      <span style={s({ "fontSize": "16px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                        {"Contact"}
                      </span>
                      <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#6f6a61", "marginLeft": "auto" })}>
                        {"4 of 4"}
                      </span>
                    </div>
                    <div style={s({ "padding": "18px 20px 16px", "boxShadow": "inset 0 -2.5px 0 #141311", "display": "flex", "flexDirection": "column", "gap": "12px" })}>
                      <span style={s({ "fontSize": "44px", "fontWeight": "700", "letterSpacing": "-.045em", "lineHeight": "1", "color": "#141311" })} className="jos-zw">
                        {"Say hello."}
                      </span>
                      <a href={V.mailto} style={s({ "display": "flex", "flexDirection": "column", "gap": "3px" })}>
                        <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                          {"Email"}
                        </span>
                        <span style={s({ "fontSize": "21px", "fontWeight": "600", "letterSpacing": "-.02em", "color": "#141311", "borderBottom": "3px solid #7ac274", "alignSelf": "flex-start", "wordBreak": "break-all" })}>
                          {V.email}
                        </span>
                      </a>
                    </div>
                    <div style={s({ "padding": "16px 20px 8px", "display": "flex", "flexDirection": "column", "gap": "14px" })}>
                      <a href={V.cvHref} download={V.cvFilename} style={s({ "display": "flex", "alignItems": "center", "gap": "12px", "background": "#7ac274", "borderRadius": "18px", "padding": "14px 14px 14px 18px", "boxShadow": "5px 6px 0 #141311" })}>
                        <div style={s({ "display": "flex", "flexDirection": "column", "gap": "1px" })}>
                          <span style={s({ "fontSize": "20px", "fontWeight": "700", "letterSpacing": "-.03em", "color": "#12300f" })}>
                            {"Download CV"}
                          </span>
                          <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#1d3d1c" })}>
                            {V.cvFilename}
                          </span>
                        </div>
                        <span style={s({ "width": "34px", "height": "34px", "borderRadius": "999px", "background": "#141311", "color": "#f4f1e6", "fontSize": "16px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none", "marginLeft": "auto" })}>
                          {"↓"}
                        </span>
                      </a>
                      <div style={s({ "display": "flex", "alignItems": "center", "gap": "10px" })}>
                        <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#5c5850" })}>
                          {"Elsewhere"}
                        </span>
                        <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                      </div>
                      <div style={s({ "display": "flex", "flexWrap": "wrap", "gap": "8px" })}>
                        {(V.socials ?? []).map((social: any, socialIndex: number) => (
                          <Fragment key={socialIndex}>
                            <a href={social.href} target="_blank" rel="noreferrer" style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#141311", "padding": "7px 13px", "borderRadius": "999px", "boxShadow": "inset 0 0 0 2.5px #141311", "transition": "background .16s,color .16s" })} className="jhmh2">
                              {social.label}
                            </a>
                          </Fragment>
                        ))}
                      </div>
                      <a href="/design" style={s({ "display": "flex", "flexDirection": "column", "alignItems": "flex-start", "gap": "3px", "paddingTop": "2px" })}>
                        <span style={s({ "fontSize": "15px", "color": "#3a3630" })}>
                          {"Client work and prices:"}
                        </span>
                        <span style={s({ "fontSize": "15px", "fontWeight": "700", "color": "#141311", "borderBottom": "2.5px solid #7ac274" })}>
                          {"jawadOS, the studio →"}
                        </span>
                      </a>
                    </div>
                    <div style={s({ "display": "flex", "alignItems": "center", "padding": "14px 20px 16px" })}>
                      <span style={s({ "fontSize": "13px", "fontWeight": "600", "color": "#5c5850" })}>
                        {"Mail goes straight to me"}
                      </span>
                    </div>
                  </div>
                </div>
                <div style={s({ "position": "absolute", "left": "16px", "right": "16px", "bottom": "22px", "zIndex": "20", "display": "flex", "alignItems": "flex-end", "justifyContent": "space-between", "background": "linear-gradient(180deg,#fbf9f1 0%,#efeadb 100%)", "boxShadow": "7px 8px 0 #141311,inset 0 2px 0 rgba(255,255,255,.9),0 26px 46px -14px rgba(4,3,8,.8)", "padding": "12px 14px 10px", "borderRadius": "24px" })}>
                  <div onClick={V.jMe} style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px", "cursor": "pointer", "flex": "1" })}>
                    <div style={s({ "width": "46px", "height": "46px", "borderRadius": "14px", "background": "#fbf9f1", "boxShadow": "4px 5px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transition": "transform .16s" })} className="jhmh3">
                      <div style={s({ "position": "relative", "width": "24px", "height": "18px", "borderRadius": "5px", "background": "#141311" })}>
                        <div style={s({ "position": "absolute", "left": "6px", "top": "-4px", "width": "10px", "height": "4px", "borderRadius": "2px 2px 0 0", "background": "#141311" })}></div>
                        <div style={s({ "position": "absolute", "left": "7px", "top": "4px", "width": "10px", "height": "10px", "borderRadius": "999px", "background": "#fbf9f1" })}></div>
                      </div>
                    </div>
                    <div style={s({ "width": "16px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav0,0)", "transition": "opacity .3s" })}></div>
                  </div>
                  <div onClick={V.jWork} style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px", "cursor": "pointer", "flex": "1" })}>
                    <div style={s({ "width": "46px", "height": "46px", "borderRadius": "14px", "background": "#fbf9f1", "boxShadow": "4px 5px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transition": "transform .16s" })} className="jhmh4">
                      <div style={s({ "position": "relative", "width": "24px", "height": "19px" })}>
                        <div style={s({ "position": "absolute", "left": "0", "top": "0", "width": "11px", "height": "5px", "borderRadius": "2px 4px 0 0", "background": "#141311" })}></div>
                        <div style={s({ "position": "absolute", "left": "0", "top": "4px", "width": "24px", "height": "15px", "borderRadius": "3px", "background": "#141311" })}></div>
                      </div>
                    </div>
                    <div style={s({ "width": "16px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav1,0)", "transition": "opacity .3s" })}></div>
                  </div>
                  <div onClick={V.jWrite} style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px", "cursor": "pointer", "flex": "1" })}>
                    <div style={s({ "width": "46px", "height": "46px", "borderRadius": "14px", "background": "#fbf9f1", "boxShadow": "4px 5px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transition": "transform .16s" })} className="jhmh5">
                      <div style={s({ "position": "relative", "width": "24px", "height": "24px" })}>
                        <div style={s({ "position": "absolute", "left": "0", "bottom": "0", "width": "24px", "height": "4px", "borderRadius": "2px", "background": "#141311" })}></div>
                        <div style={s({ "position": "absolute", "left": "3px", "bottom": "7px", "width": "16px", "height": "5px", "background": "#141311", "transform": "rotate(-42deg)", "transformOrigin": "left center" })}></div>
                        <div style={s({ "position": "absolute", "left": "17px", "top": "1px", "width": "7px", "height": "7px", "borderRadius": "2px", "background": "#141311" })}></div>
                      </div>
                    </div>
                    <div style={s({ "width": "16px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav2,0)", "transition": "opacity .3s" })}></div>
                  </div>
                  <div onClick={V.jMail} style={s({ "position": "relative", "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px", "cursor": "pointer", "flex": "1" })}>
                    <div style={s({ "width": "46px", "height": "46px", "borderRadius": "14px", "background": "#fbf9f1", "boxShadow": "4px 5px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transition": "transform .16s" })} className="jhmh6">
                      <div style={s({ "position": "relative", "width": "24px", "height": "17px", "borderRadius": "3px", "background": "#141311", "overflow": "hidden" })}>
                        <div style={s({ "position": "absolute", "left": "1px", "top": "1px", "width": "22px", "height": "11px", "background": "#fbf9f1", "clipPath": "polygon(0 0,100% 0,50% 100%)" })}></div>
                      </div>
                    </div>
                    <div style={s({ "width": "16px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav3,0)", "transition": "opacity .3s" })}></div>
                  </div>
                </div>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "top": "0", "height": "52px", "background": "linear-gradient(180deg,#211e1a 0%,#151412 58%,#0d0c0a 100%)", "zIndex": "22", "display": "flex", "alignItems": "center", "justifyContent": "space-between", "padding": "0 18px", "boxShadow": "inset 0 1.5px 0 rgba(244,241,230,.1),0 14px 26px -12px rgba(0,0,0,.85)" })}>
                  <div onClick={V.jTop} style={s({ "display": "flex", "alignItems": "center", "gap": "9px", "cursor": "pointer" })}>
                    <div style={s({ "width": "12px", "height": "12px", "background": "#7ac274", "borderRadius": "3px", "transform": "rotate(45deg)", "boxShadow": "0 0 14px rgba(122,194,116,.75)" })}></div>
                    <span style={s({ "fontSize": "15px", "fontWeight": "700", "letterSpacing": "-.01em", "color": "#f4f1e6" })}>
                      {"jawadOS"}
                    </span>
                  </div>
                  <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#8d887d", "fontVariantNumeric": "tabular-nums" })}>
                    {V.clock}
                  </span>
                </div>
                <a href="/design" style={s({ "position": "absolute", "left": "50%", "top": "8px", "transform": "translateX(-50%)", "height": "34px", "background": "#7ac274", "borderRadius": "999px", "zIndex": "24", "display": "flex", "alignItems": "center", "gap": "9px", "padding": "0 15px", "boxShadow": "inset 0 0 0 1px rgba(255,255,255,.28),0 3px 0 #4b8546,0 8px 20px -4px rgba(122,194,116,.7)", "transition": "transform .2s cubic-bezier(.3,1.3,.4,1),box-shadow .2s,background .2s" })} className="jhmh7">
                  <div style={s({ "width": "8px", "height": "8px", "borderRadius": "999px", "background": "#12300f", "flex": "none", "animation": "hum 2.6s ease-in-out infinite" })}></div>
                  <span style={s({ "fontSize": "14px", "fontWeight": "700", "letterSpacing": "-.01em", "color": "#12300f", "whiteSpace": "nowrap" })}>
                    {"The studio"}
                  </span>
                </a>
                <div style={s({ "position": "absolute", "left": "0", "right": "0", "top": "0", "height": "300px", "background": "linear-gradient(160deg,rgba(255,255,255,.14) 0%,rgba(255,255,255,.04) 42%,transparent 60%)", "pointerEvents": "none", "zIndex": "26" })}></div>
                <div style={s({ "position": "absolute", "inset": "0", "zIndex": "27", "pointerEvents": "none", "background": "radial-gradient(120% 108% at 50% 48%,rgba(0,0,0,0) 58%,rgba(0,0,0,.3) 100%)" })}></div>
                <div style={s({ "position": "absolute", "left": "50%", "bottom": "9px", "transform": "translateX(-50%)", "width": "132px", "height": "5px", "borderRadius": "999px", "background": "rgba(244,241,230,.5)", "zIndex": "28", "pointerEvents": "none" })}></div>
              </div>
            </div>
          </div>
          <div style={s({ "position": "absolute", "inset": "0", "pointerEvents": "none", "background": "radial-gradient(74% 72% at 50% 46%,rgba(0,0,0,0) 40%,rgba(0,0,0,.5) 82%,rgba(0,0,0,.74) 100%)" })}></div>
        </div>
      </div>
    </>
  );
}
