// GENERATED by scripts/build-design-scene.mjs from design/templates.
// Do not edit by hand — edit the template and re-run `npm run design:scene`.
/* eslint-disable @next/next/no-img-element */
import { Fragment, type CSSProperties } from "react";

// The scene leans on CSS custom properties for every animated value, so most
// declarations are var()/calc() strings that React's own CSSProperties types
// reject on principle. One cast at the boundary beats 1200 of them.
const s = (o: Record<string, string | number>) => o as CSSProperties;

export const SceneHomeDesktopHover = ".jhdh0:hover{animation:squish .5s cubic-bezier(.3,1.3,.4,1) forwards}\n.jhdh1:hover{animation:squish .5s cubic-bezier(.3,1.3,.4,1) forwards}\n.jhdh2:hover{transform:scale(1.35)}\n.jhdh3:hover{color:#141311}\n.jhdh4:hover{color:#141311}\n.jhdh5:hover{transform:translate(-3px,-4px)}\n.jhdh6:hover{transform:translate(-2px,-3px)}\n.jhdh7:hover{transform:scale(1.35)}\n.jhdh8:hover{color:#141311}\n.jhdh9:hover{color:#141311}\n.jhdh10:hover{transform:translateY(-5px)}\n.jhdh11:hover{transform:translateX(5px)}\n.jhdh12:hover{transform:translateY(-2px)}\n.jhdh13:hover{transform:scale(1.35)}\n.jhdh14:hover{color:#141311}\n.jhdh15:hover{color:#141311}\n.jhdh16:hover{transform:translateX(5px)}\n.jhdh17:hover{transform:translate(-3px,-4px)}\n.jhdh18:hover{transform:translate(-2px,-3px)}\n.jhdh19:hover{transform:scale(1.35)}\n.jhdh20:hover{color:#141311}\n.jhdh21:hover{color:#141311}\n.jhdh22:hover{transform:translateX(4px)}\n.jhdh23:hover{transform:translate(-3px,-4px)}\n.jhdh24:hover{transform:translateY(-3px);box-shadow:inset 0 0 0 2.5px #141311,0 4px 0 #141311}\n.jhdh25:hover{animation:squish .5s cubic-bezier(.3,1.3,.4,1) forwards}\n.jhdh26:hover{animation:squish .5s cubic-bezier(.3,1.3,.4,1) forwards}\n.jhdh27:hover{animation:squish .5s cubic-bezier(.3,1.3,.4,1) forwards}\n.jhdh28:hover{animation:squish .5s cubic-bezier(.3,1.3,.4,1) forwards}\n.jhdh29:hover{background:rgba(244,241,230,.1)}\n.jhdh30:hover{opacity:1;background:rgba(244,241,230,.17)}\n.jhdh31:hover{opacity:1;background:rgba(244,241,230,.17)}\n.jhdh32:hover{opacity:1;background:rgba(244,241,230,.17)}\n.jhdh33:hover{opacity:1;background:rgba(244,241,230,.17)}\n.jhdh34:hover{color:#f4f1e6;background:rgba(244,241,230,.1)}\n.jhdh35:hover{transform:translateY(-2px);box-shadow:0 5px 0 #4b8546,0 14px 26px -6px rgba(122,194,116,.8)}";

export function SceneHomeDesktop({ V }: { V: any }) {
  return (
    <>
      <style>{SceneHomeDesktopHover}</style>
      <div style={s({ "height": "700vh", "position": "relative", "background": "#0f0e0c" })}>
        <div ref={V.refRoom} style={s({ "position": "sticky", "top": "0", "height": "100vh", "overflow": "hidden", "cursor": "none", "perspective": "2000px", "perspectiveOrigin": "50% 46%", "background": "radial-gradient(132% 122% at 50% 36%,#26263d 0%,#15141f 44%,#0a0910 76%,#060509 100%)" })}>
          <div style={s({ "position": "absolute", "inset": "0", "background": "radial-gradient(58% 52% at 50% 44%,rgba(120,150,210,.24) 0%,rgba(13,11,20,0) 72%)", "pointerEvents": "none" })}></div>
          <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "0", "height": "38%", "background": "linear-gradient(180deg,rgba(4,3,8,0) 0%,rgba(4,3,8,.5) 62%,rgba(4,3,8,.82) 100%)", "pointerEvents": "none" })}></div>
          <div ref={V.refWorldWrap} style={s({ "position": "absolute", "left": "50%", "top": "50%", "width": "1502px", "height": "962px", "transform": "translate(-50%,-50%) scale(var(--fit,1)) rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg))", "transformStyle": "preserve-3d", "willChange": "transform" })}>
            <div style={s({ "position": "absolute", "left": "6%", "right": "6%", "bottom": "-70px", "height": "120px", "background": "radial-gradient(ellipse at center,rgba(0,0,0,.62) 0%,rgba(0,0,0,0) 72%)", "filter": "blur(2px)" })}></div>
            <div style={s({ "position": "relative", "padding": "16px", "borderRadius": "26px", "border": "2px solid #6d6a63", "background": "linear-gradient(180deg,#f0eee7 0%,#d8d5cd 34%,#bcb9b1 72%,#9d9a93 100%)", "boxShadow": "inset 0 3px 0 rgba(255,255,255,.95),inset 3px 0 0 rgba(255,255,255,.55),inset -3px 0 0 rgba(20,18,31,.16),inset 0 -7px 0 rgba(20,18,31,.24),0 7px 0 #8b887f,0 13px 0 #6b6862,0 22px 26px rgba(4,3,8,.5),0 60px 80px rgba(4,3,8,.62),0 120px 150px rgba(4,3,8,.5)" })}>
              <div style={s({ "padding": "13px", "borderRadius": "18px", "background": "linear-gradient(180deg,#151322 0%,#08070d 100%)", "boxShadow": "inset 0 0 0 2px #2c2939,inset 0 4px 14px rgba(0,0,0,.98),inset 0 -2px 0 rgba(255,255,255,.07)" })}>
                <div ref={V.refScreen} style={s({ "position": "relative", "width": "1440px", "height": "900px", "background": "#0f0e0c", "overflow": "hidden", "borderRadius": "8px" })} className="jos-crt">
                  <div className="jos-scanline"></div>
                  <div style={s({ "position": "absolute", "inset": "0", "background": "linear-gradient(var(--sky-top,#0b0d0b) 0%,var(--sky-mid,#121a13) 46%,var(--sky-bot,#1f2e20) 100%)", "transition": "background 1.1s ease" })}></div>
                  <div style={s({ "position": "absolute", "inset": "0", "background": "radial-gradient(62% 46% at 50% 88%,var(--glow,#7ac274) 0%,rgba(0,0,0,0) 70%)", "opacity": ".16", "transition": "background 1.1s ease", "pointerEvents": "none" })}></div>
                  <div style={s({ "position": "absolute", "inset": "0", "opacity": "var(--star-op,0)" })}>
                    <div style={s({ "position": "absolute", "left": "9%", "top": "11%", "width": "4px", "height": "4px", "background": "#fff", "animation": "twinkle 3s ease-in-out infinite" })}></div>
                    <div style={s({ "position": "absolute", "left": "23%", "top": "20%", "width": "4px", "height": "4px", "background": "#fff", "animation": "twinkle 4.5s ease-in-out infinite" })}></div>
                    <div style={s({ "position": "absolute", "left": "38%", "top": "8%", "width": "4px", "height": "4px", "background": "#fff", "animation": "twinkle 3.8s ease-in-out infinite" })}></div>
                    <div style={s({ "position": "absolute", "left": "57%", "top": "15%", "width": "4px", "height": "4px", "background": "#fff", "animation": "twinkle 5.2s ease-in-out infinite" })}></div>
                    <div style={s({ "position": "absolute", "left": "71%", "top": "9%", "width": "4px", "height": "4px", "background": "#fff", "animation": "twinkle 3.2s ease-in-out infinite" })}></div>
                    <div style={s({ "position": "absolute", "left": "86%", "top": "18%", "width": "4px", "height": "4px", "background": "#fff", "animation": "twinkle 4.1s ease-in-out infinite" })}></div>
                    <div style={s({ "position": "absolute", "left": "48%", "top": "26%", "width": "4px", "height": "4px", "background": "#fff", "animation": "twinkle 4.8s ease-in-out infinite" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "right": "9%", "top": "9%", "width": "76px", "height": "76px", "background": "var(--sun,#fff0a8)", "opacity": "var(--sun-op,0)", "clipPath": "polygon(37% 0,63% 0,63% 4%,79% 4%,79% 12%,90% 12%,90% 21%,96% 21%,96% 37%,100% 37%,100% 63%,96% 63%,96% 79%,90% 79%,90% 88%,79% 88%,79% 96%,63% 96%,63% 100%,37% 100%,37% 96%,21% 96%,21% 88%,10% 88%,10% 79%,4% 79%,4% 63%,0 63%,0 37%,4% 37%,4% 21%,10% 21%,10% 12%,21% 12%,21% 4%,37% 4%)" })}></div>
                  <div style={s({ "position": "absolute", "left": "8%", "top": "12%", "animation": "drift 18s ease-in-out infinite alternate", "opacity": "var(--cloud-op,1)" })}>
                    <div style={s({ "width": "132px", "height": "18px", "background": "#8d887d" })}></div>
                    <div style={s({ "width": "118px", "height": "10px", "background": "#6f6a61", "position": "absolute", "left": "8px", "top": "18px" })}></div>
                    <div style={s({ "width": "72px", "height": "20px", "background": "#fff", "position": "absolute", "left": "26px", "top": "-20px" })}></div>
                    <div style={s({ "width": "38px", "height": "12px", "background": "#fff", "position": "absolute", "left": "46px", "top": "-32px" })}></div>
                    <div style={s({ "width": "26px", "height": "12px", "background": "#fff", "position": "absolute", "left": "-20px", "top": "10px" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "59%", "top": "18%", "animation": "drift 24s ease-in-out infinite alternate-reverse", "opacity": "var(--cloud-op,1)" })}>
                    <div style={s({ "width": "158px", "height": "20px", "background": "#8d887d" })}></div>
                    <div style={s({ "width": "142px", "height": "10px", "background": "#6f6a61", "position": "absolute", "left": "8px", "top": "20px" })}></div>
                    <div style={s({ "width": "82px", "height": "20px", "background": "#fff", "position": "absolute", "left": "36px", "top": "-20px" })}></div>
                    <div style={s({ "width": "44px", "height": "12px", "background": "#fff", "position": "absolute", "left": "58px", "top": "-32px" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "-3%", "right": "-3%", "bottom": "196px", "height": "300px", "transform": "translateX(calc(var(--p,0) * -78px))" })}>
                    <div style={s({ "position": "absolute", "left": "3%", "bottom": "0", "width": "70px", "height": "150px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-far,#8fb8d8) 0 12px,transparent 12px 18px),repeating-linear-gradient(90deg,rgba(255,233,168,calc(var(--lit,0) * .55)) 0 6px,transparent 6px 16px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "9%", "bottom": "0", "width": "54px", "height": "112px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                    <div style={s({ "position": "absolute", "left": "14%", "bottom": "0", "width": "86px", "height": "186px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-far,#8fb8d8) 0 12px,transparent 12px 18px),repeating-linear-gradient(90deg,rgba(255,233,168,calc(var(--lit,0) * .55)) 0 6px,transparent 6px 16px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "21%", "bottom": "0", "width": "44px", "height": "128px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                    <div style={s({ "position": "absolute", "left": "26%", "bottom": "0", "width": "78px", "height": "250px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "clipPath": "polygon(46% 0,54% 0,100% 100%,0 100%)" })}></div>
                    <div style={s({ "position": "absolute", "left": "34%", "bottom": "0", "width": "62px", "height": "160px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                    <div style={s({ "position": "absolute", "left": "40%", "bottom": "0", "width": "64px", "height": "196px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "clipPath": "polygon(18% 100%,18% 30%,32% 30%,32% 16%,44% 16%,44% 6%,56% 6%,56% 16%,68% 16%,68% 30%,82% 30%,82% 100%)" })}></div>
                    <div style={s({ "position": "absolute", "left": "46%", "bottom": "0", "width": "74px", "height": "120px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                    <div style={s({ "position": "absolute", "left": "53%", "bottom": "0", "width": "58px", "height": "172px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "clipPath": "polygon(0 0,100% 14%,100% 100%,0 100%)" })}></div>
                    <div style={s({ "position": "absolute", "left": "60%", "bottom": "0", "width": "88px", "height": "134px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-far,#8fb8d8) 0 12px,transparent 12px 18px),repeating-linear-gradient(90deg,rgba(255,233,168,calc(var(--lit,0) * .55)) 0 6px,transparent 6px 16px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "69%", "bottom": "0", "width": "50px", "height": "206px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                    <div style={s({ "position": "absolute", "left": "75%", "bottom": "0", "width": "80px", "height": "150px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-far,#8fb8d8) 0 12px,transparent 12px 18px),repeating-linear-gradient(90deg,rgba(255,233,168,calc(var(--lit,0) * .55)) 0 6px,transparent 6px 16px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "83%", "bottom": "0", "width": "60px", "height": "184px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                    <div style={s({ "position": "absolute", "left": "90%", "bottom": "0", "width": "74px", "height": "126px", "transition": "background 1.1s ease", "background": "var(--city-far,#1a231b)" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "-2%", "right": "-2%", "bottom": "196px", "height": "340px", "transform": "translateX(calc(var(--p,0) * -150px))" })}>
                    <div style={s({ "position": "absolute", "left": "1%", "bottom": "0", "width": "62px", "height": "88px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-near,#3f6f96) 0 11px,transparent 11px 17px),repeating-linear-gradient(90deg,rgba(255,233,168,var(--lit,0)) 0 7px,transparent 7px 15px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "5.4%", "bottom": "0", "width": "46px", "height": "120px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-near,#3f6f96) 0 11px,transparent 11px 17px),repeating-linear-gradient(90deg,rgba(255,233,168,var(--lit,0)) 0 7px,transparent 7px 15px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "9.6%", "bottom": "0", "width": "104px", "height": "104px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "9.6%", "bottom": "104px", "width": "104px", "height": "54px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(0 100%,0 62%,10% 62%,10% 40%,26% 40%,26% 20%,44% 20%,44% 8%,56% 8%,56% 20%,74% 20%,74% 40%,90% 40%,90% 62%,100% 62%,100% 100%)" })}></div>
                    <div style={s({ "position": "absolute", "left": "13.2%", "bottom": "158px", "width": "16px", "height": "18px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "14%", "bottom": "176px", "width": "6px", "height": "14px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "22%", "bottom": "0", "width": "58px", "height": "236px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "22%", "bottom": "236px", "width": "58px", "height": "52px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(42% 0,58% 0,58% 22%,72% 22%,72% 52%,86% 52%,86% 78%,100% 78%,100% 100%,0 100%,0 78%,14% 78%,14% 52%,28% 52%,28% 22%,42% 22%)" })}></div>
                    <div style={s({ "position": "absolute", "left": "22.7%", "bottom": "188px", "width": "38px", "height": "38px", "background": "#ffe9a8", "opacity": "var(--lit,.85)" })}></div>
                    <div style={s({ "position": "absolute", "left": "23.5%", "bottom": "196px", "width": "22px", "height": "22px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "34%", "bottom": "0", "width": "300px", "height": "184px" })}>
                      <div style={s({ "position": "absolute", "left": "0", "bottom": "0", "width": "38px", "height": "150px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                      <div style={s({ "position": "absolute", "left": "0", "bottom": "150px", "width": "38px", "height": "34px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(38% 0,62% 0,62% 30%,80% 30%,80% 64%,100% 64%,100% 100%,0 100%,0 64%,20% 64%,20% 30%,38% 30%)" })}></div>
                      <div style={s({ "position": "absolute", "right": "0", "bottom": "0", "width": "38px", "height": "150px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                      <div style={s({ "position": "absolute", "right": "0", "bottom": "150px", "width": "38px", "height": "34px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(38% 0,62% 0,62% 30%,80% 30%,80% 64%,100% 64%,100% 100%,0 100%,0 64%,20% 64%,20% 30%,38% 30%)" })}></div>
                      <div style={s({ "position": "absolute", "left": "0", "bottom": "24px", "width": "300px", "height": "14px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                      <div style={s({ "position": "absolute", "left": "38px", "bottom": "38px", "width": "224px", "height": "74px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(0 100%,0 46%,12% 46%,12% 24%,28% 24%,28% 8%,44% 8%,44% 0,56% 0,56% 8%,72% 8%,72% 24%,88% 24%,88% 46%,100% 46%,100% 100%,88% 100%,88% 62%,72% 62%,72% 40%,56% 40%,56% 26%,44% 26%,44% 40%,28% 40%,28% 62%,12% 62%,12% 100%)" })}></div>
                      <div style={s({ "position": "absolute", "left": "0", "bottom": "38px", "width": "300px", "height": "8px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "59%", "bottom": "0", "width": "210px", "height": "300px" })}>
                      <div style={s({ "position": "absolute", "left": "10px", "bottom": "96px", "width": "190px", "height": "190px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "clipPath": "polygon(37% 0,63% 0,63% 4%,79% 4%,79% 12%,90% 12%,90% 21%,96% 21%,96% 37%,100% 37%,100% 63%,96% 63%,96% 79%,90% 79%,90% 88%,79% 88%,79% 96%,63% 96%,63% 100%,37% 100%,37% 96%,21% 96%,21% 88%,10% 88%,10% 79%,4% 79%,4% 63%,0 63%,0 37%,4% 37%,4% 21%,10% 21%,10% 12%,21% 12%,21% 4%,37% 4%)" })}></div>
                      <div style={s({ "position": "absolute", "left": "34px", "bottom": "120px", "width": "142px", "height": "142px", "background": "var(--sky-mid,#9fdcff)", "clipPath": "polygon(37% 0,63% 0,63% 4%,79% 4%,79% 12%,90% 12%,90% 21%,96% 21%,96% 37%,100% 37%,100% 63%,96% 63%,96% 79%,90% 79%,90% 88%,79% 88%,79% 96%,63% 96%,63% 100%,37% 100%,37% 96%,21% 96%,21% 88%,10% 88%,10% 79%,4% 79%,4% 63%,0 63%,0 37%,4% 37%,4% 21%,10% 21%,10% 12%,21% 12%,21% 4%,37% 4%)" })}></div>
                      <div style={s({ "position": "absolute", "left": "96px", "bottom": "182px", "width": "18px", "height": "18px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                      <div style={s({ "position": "absolute", "left": "96px", "bottom": "60px", "width": "9px", "height": "130px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                      <div style={s({ "position": "absolute", "left": "64px", "bottom": "0", "width": "12px", "height": "104px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                      <div style={s({ "position": "absolute", "left": "126px", "bottom": "0", "width": "12px", "height": "104px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                      <div style={s({ "position": "absolute", "left": "52px", "bottom": "0", "width": "110px", "height": "12px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "79%", "bottom": "0", "width": "86px", "height": "112px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-near,#3f6f96) 0 11px,transparent 11px 17px),repeating-linear-gradient(90deg,rgba(255,233,168,var(--lit,0)) 0 7px,transparent 7px 15px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "86%", "bottom": "0", "width": "54px", "height": "164px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-near,#3f6f96) 0 11px,transparent 11px 17px),repeating-linear-gradient(90deg,rgba(255,233,168,var(--lit,0)) 0 7px,transparent 7px 15px)" })}></div>
                    <div style={s({ "position": "absolute", "left": "92%", "bottom": "0", "width": "72px", "height": "98px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)", "backgroundImage": "repeating-linear-gradient(0deg,var(--city-near,#3f6f96) 0 11px,transparent 11px 17px),repeating-linear-gradient(90deg,rgba(255,233,168,var(--lit,0)) 0 7px,transparent 7px 15px)" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "14%", "bottom": "132px", "width": "96px", "height": "34px", "zIndex": "2", "opacity": ".92" })}>
                    <div style={s({ "position": "absolute", "left": "0", "bottom": "0", "width": "96px", "height": "12px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "10px", "bottom": "12px", "width": "60px", "height": "10px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "22px", "bottom": "22px", "width": "30px", "height": "8px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "60px", "bottom": "22px", "width": "6px", "height": "12px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "-8px", "bottom": "2px", "width": "22px", "height": "5px", "background": "var(--river-lit,#9ccbe8)" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "right": "22%", "bottom": "112px", "width": "70px", "height": "26px", "zIndex": "2", "opacity": ".85" })}>
                    <div style={s({ "position": "absolute", "left": "0", "bottom": "0", "width": "70px", "height": "10px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "8px", "bottom": "10px", "width": "40px", "height": "8px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "left": "44px", "bottom": "10px", "width": "5px", "height": "14px", "transition": "background 1.1s ease", "background": "var(--city-near,#0f1411)" })}></div>
                    <div style={s({ "position": "absolute", "right": "-10px", "bottom": "1px", "width": "18px", "height": "4px", "background": "var(--river-lit,#9ccbe8)" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "96px", "height": "100px", "background": "var(--river,#6fa8cf)" })}></div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "150px", "height": "8px", "background": "var(--river-lit,#9ccbe8)", "opacity": ".7" })}></div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "124px", "height": "6px", "background": "var(--river-lit,#9ccbe8)", "opacity": ".45" })}></div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "190px", "height": "10px", "background": "var(--embank,#4f5b66)" })}></div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "0", "height": "96px", "background": "var(--fore,#4a5560)" })}></div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "96px", "height": "44px", "display": "flex", "justifyContent": "space-around", "alignItems": "flex-end", "pointerEvents": "none" })}>
                    <div style={s({ "position": "relative", "width": "10px", "height": "44px", "background": "var(--fore-lit,#5f6b76)" })}>
                      <div style={s({ "position": "absolute", "left": "-5px", "top": "-10px", "width": "20px", "height": "12px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                      <div style={s({ "position": "absolute", "left": "-1px", "top": "-6px", "width": "12px", "height": "6px", "background": "rgba(255,233,168,var(--lit,0))" })}></div>
                    </div>
                    <div style={s({ "position": "relative", "width": "10px", "height": "44px", "background": "var(--fore-lit,#5f6b76)" })}>
                      <div style={s({ "position": "absolute", "left": "-5px", "top": "-10px", "width": "20px", "height": "12px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                      <div style={s({ "position": "absolute", "left": "-1px", "top": "-6px", "width": "12px", "height": "6px", "background": "rgba(255,233,168,var(--lit,0))" })}></div>
                    </div>
                    <div style={s({ "position": "relative", "width": "10px", "height": "44px", "background": "var(--fore-lit,#5f6b76)" })}>
                      <div style={s({ "position": "absolute", "left": "-5px", "top": "-10px", "width": "20px", "height": "12px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                      <div style={s({ "position": "absolute", "left": "-1px", "top": "-6px", "width": "12px", "height": "6px", "background": "rgba(255,233,168,var(--lit,0))" })}></div>
                    </div>
                    <div style={s({ "position": "relative", "width": "10px", "height": "44px", "background": "var(--fore-lit,#5f6b76)" })}>
                      <div style={s({ "position": "absolute", "left": "-5px", "top": "-10px", "width": "20px", "height": "12px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                      <div style={s({ "position": "absolute", "left": "-1px", "top": "-6px", "width": "12px", "height": "6px", "background": "rgba(255,233,168,var(--lit,0))" })}></div>
                    </div>
                    <div style={s({ "position": "relative", "width": "10px", "height": "44px", "background": "var(--fore-lit,#5f6b76)" })}>
                      <div style={s({ "position": "absolute", "left": "-5px", "top": "-10px", "width": "20px", "height": "12px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                      <div style={s({ "position": "absolute", "left": "-1px", "top": "-6px", "width": "12px", "height": "6px", "background": "rgba(255,233,168,var(--lit,0))" })}></div>
                    </div>
                    <div style={s({ "position": "relative", "width": "10px", "height": "44px", "background": "var(--fore-lit,#5f6b76)" })}>
                      <div style={s({ "position": "absolute", "left": "-5px", "top": "-10px", "width": "20px", "height": "12px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                      <div style={s({ "position": "absolute", "left": "-1px", "top": "-6px", "width": "12px", "height": "6px", "background": "rgba(255,233,168,var(--lit,0))" })}></div>
                    </div>
                    <div style={s({ "position": "relative", "width": "10px", "height": "44px", "background": "var(--fore-lit,#5f6b76)" })}>
                      <div style={s({ "position": "absolute", "left": "-5px", "top": "-10px", "width": "20px", "height": "12px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                      <div style={s({ "position": "absolute", "left": "-1px", "top": "-6px", "width": "12px", "height": "6px", "background": "rgba(255,233,168,var(--lit,0))" })}></div>
                    </div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "bottom": "88px", "height": "8px", "background": "var(--fore-lit,#5f6b76)" })}></div>
                  <div ref={V.refWorld} style={s({ "position": "absolute", "left": "0", "top": "0", "width": "1440px", "height": "900px" })}>
                    <div style={s({ "position": "absolute", "left": "34px", "bottom": "30px", "display": "flex", "alignItems": "flex-end", "gap": "24px", "zIndex": "4" })}>
                      <div onClick={V.jMe} style={s({ "width": "104px", "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "10px", "cursor": "none" })}>
                        <div style={s({ "width": "62px", "height": "62px", "borderRadius": "18px", "background": "#fbf9f1", "boxShadow": "5px 6px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transformOrigin": "50% 100%" })} className="jhdh0">
                          <div style={s({ "position": "relative", "width": "34px", "height": "25px", "borderRadius": "6px", "background": "#141311" })}>
                            <div style={s({ "position": "absolute", "left": "9px", "top": "-5px", "width": "13px", "height": "5px", "borderRadius": "3px 3px 0 0", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "left": "10px", "top": "6px", "width": "14px", "height": "14px", "borderRadius": "999px", "background": "#fbf9f1" })}></div>
                            <div style={s({ "position": "absolute", "left": "13px", "top": "9px", "width": "8px", "height": "8px", "borderRadius": "999px", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "right": "4px", "top": "4px", "width": "4px", "height": "4px", "borderRadius": "999px", "background": "#fbf9f1" })}></div>
                          </div>
                        </div>
                        <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#f4f1e6", "background": "#141311", "borderRadius": "999px", "padding": "4px 11px" })}>
                          {"Me"}
                        </span>
                      </div>
                      <div onClick={V.jWork} style={s({ "width": "104px", "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "10px", "cursor": "none" })}>
                        <div style={s({ "width": "62px", "height": "62px", "borderRadius": "18px", "background": "#fbf9f1", "boxShadow": "5px 6px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transformOrigin": "50% 100%" })} className="jhdh1">
                          <div style={s({ "position": "relative", "width": "34px", "height": "27px" })}>
                            <div style={s({ "position": "absolute", "left": "0", "top": "0", "width": "16px", "height": "7px", "borderRadius": "3px 5px 0 0", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "left": "0", "top": "5px", "width": "34px", "height": "22px", "borderRadius": "4px", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "left": "4px", "top": "13px", "width": "26px", "height": "3px", "borderRadius": "2px", "background": "#fbf9f1" })}></div>
                          </div>
                        </div>
                        <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#f4f1e6", "background": "#141311", "borderRadius": "999px", "padding": "4px 11px" })}>
                          {"Experience"}
                        </span>
                      </div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "100px", "top": "104px", "width": "1240px", "zIndex": "10", "pointerEvents": "var(--pe0,auto)", "transformOrigin": "633px 700px", "opacity": "calc(1 - clamp(0, (var(--p,0) - .2) * 12, 1))", "transform": "scale(calc(1.1 - 1.06 * clamp(0, (var(--p,0) - .2) * 12, 1)))" })} className="jos-z0">
                      <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "16px 18px 0 #141311,0 36px 74px -28px rgba(13,11,20,.55)", "opacity": "var(--w0,1)", "transform": "scale(calc(.72 + .28 * var(--w0,1)))", "transition": "opacity .3s ease,transform .3s cubic-bezier(.3,0,.6,1)" })}>
                        <div style={s({ "height": "56px", "display": "flex", "alignItems": "center", "gap": "22px", "padding": "0 20px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                          <div onClick={V.close0} style={s({ "width": "14px", "height": "14px", "borderRadius": "999px", "background": "#141311", "cursor": "none", "flex": "none", "transition": "transform .14s" })} className="jhdh2"></div>
                          <span style={s({ "fontSize": "18px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                            {"Me"}
                          </span>
                          <div style={s({ "display": "flex", "alignItems": "center", "gap": "22px", "marginLeft": "auto" })}>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh3">
                              {"File"}
                            </span>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh4">
                              {"View"}
                            </span>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "center", "gap": "14px", "padding": "20px 42px 0" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "700", "letterSpacing": ".16em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                            {"Personal site, 2026"}
                          </span>
                          <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                          <div style={s({ "width": "10px", "height": "10px", "borderRadius": "999px", "background": "#7ac274" })}></div>
                          <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850" })}>
                            {V.nowLine}
                          </span>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "flex-start", "gap": "38px", "padding": "10px 42px 34px" })}>
                          <div style={s({ "flex": "1", "minWidth": "0", "display": "flex", "flexDirection": "column", "gap": "16px" })}>
                            <div style={s({ "display": "flex", "flexDirection": "column" })}>
                              <span style={s({ "fontSize": "132px", "fontWeight": "700", "letterSpacing": "-.06em", "lineHeight": ".86", "color": "#141311", "animation": "hit .52s cubic-bezier(.34,1.56,.64,1) both" })}>
                                {"JAWAD"}
                              </span>
                              <span style={s({ "fontSize": "132px", "fontWeight": "700", "letterSpacing": "-.06em", "lineHeight": ".86", "color": "#141311", "animation": "hit .52s .09s cubic-bezier(.34,1.56,.64,1) both" })}>
                                {"JALAL"}
                              </span>
                            </div>
                            <span style={s({ "fontSize": "38px", "fontWeight": "600", "letterSpacing": "-.035em", "lineHeight": "1.05", "color": "#5c5850", "animation": "rise .45s .22s ease-out both" })}>
                              {"Designer and Founder. Building the good‑looking."}
                            </span>
                            <p style={s({ "margin": "0", "maxWidth": "600px", "fontSize": "19px", "lineHeight": "1.5", "color": "#3a3630", "textWrap": "pretty", "animation": "rise .5s .3s ease-out both" })}>
                              {V.bio}
                            </p>
                            <div style={s({ "display": "flex", "alignItems": "center", "gap": "16px", "animation": "rise .5s .38s ease-out both" })}>
                              <div onClick={V.jWork} style={s({ "display": "flex", "alignItems": "center", "gap": "22px", "background": "#7ac274", "borderRadius": "22px", "padding": "16px 18px 16px 26px", "boxShadow": "8px 9px 0 #141311", "cursor": "none", "transition": "transform .18s cubic-bezier(.2,.9,.3,1)" })} className="jhdh5">
                                <div style={s({ "display": "flex", "flexDirection": "column", "gap": "2px" })}>
                                  <span style={s({ "fontSize": "30px", "fontWeight": "700", "letterSpacing": "-.035em", "lineHeight": "1", "color": "#12300f" })}>
                                    {"What I have built"}
                                  </span>
                                  <span style={s({ "fontSize": "16px", "fontWeight": "600", "color": "#1d3d1c" })}>
                                    {V.builtLine}
                                  </span>
                                </div>
                                <div style={s({ "position": "relative", "width": "48px", "height": "48px", "borderRadius": "999px", "background": "#141311", "flex": "none" })}>
                                  <div style={s({ "position": "absolute", "left": "17px", "top": "15px", "width": "12px", "height": "2.5px", "background": "#f4f1e6", "transform": "rotate(45deg)", "transformOrigin": "left center" })}></div>
                                  <div style={s({ "position": "absolute", "left": "17px", "top": "32px", "width": "12px", "height": "2.5px", "background": "#f4f1e6", "transform": "rotate(-45deg)", "transformOrigin": "left center" })}></div>
                                </div>
                              </div>
                              <a href={V.cvHref} download={V.cvFilename} style={s({ "display": "flex", "alignItems": "center", "gap": "12px", "borderRadius": "999px", "padding": "13px 13px 13px 21px", "boxShadow": "inset 0 0 0 2.5px #141311", "cursor": "none", "transition": "transform .16s cubic-bezier(.2,.9,.3,1)" })} className="jhdh6">
                                <span style={s({ "fontSize": "18px", "fontWeight": "700", "color": "#141311" })}>
                                  {"Download CV"}
                                </span>
                                <span style={s({ "width": "30px", "height": "30px", "borderRadius": "999px", "background": "#141311", "color": "#f4f1e6", "fontSize": "16px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none" })}>
                                  {"↓"}
                                </span>
                              </a>
                            </div>
                          </div>
                          <div style={s({ "width": "300px", "flex": "none", "display": "flex", "flexDirection": "column", "gap": "16px", "animation": "rise .5s .44s ease-out both" })}>
                            <div style={s({ "width": "300px", "height": "300px", "borderRadius": "999px", "overflow": "hidden", "background": "#e6e1d3", "boxShadow": "10px 11px 0 #141311" })}>
                              <img src="/assets/portrait.png" alt="Jawad Jalal" style={s({ "width": "100%", "height": "100%", "objectFit": "cover", "display": "block" })} />
                            </div>
                            <div style={s({ "transform": "rotate(2deg)", "background": "#fbf9f1", "borderRadius": "18px", "padding": "14px 18px", "boxShadow": "8px 9px 0 #141311", "display": "flex", "flexDirection": "column", "gap": "3px" })}>
                              <span style={s({ "fontSize": "13px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                                {"Where"}
                              </span>
                              <span style={s({ "fontSize": "18px", "fontWeight": "600", "color": "#141311" })}>
                                {"London, England"}
                              </span>
                            </div>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "center", "gap": "14px", "padding": "12px 22px", "boxShadow": "inset 0 2.5px 0 #141311" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Scroll to open the rest"}
                          </span>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850", "marginLeft": "auto" })}>
                            {"1 of 4 windows"}
                          </span>
                        </div>
                      </div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "100px", "top": "104px", "width": "1240px", "zIndex": "11", "pointerEvents": "var(--pe1,none)", "transformOrigin": "633px 700px", "opacity": "calc(clamp(0, (var(--p,0) - .21) * 12, 1) - clamp(0, (var(--p,0) - .45) * 12, 1))", "transform": "scale(calc(.04 + 1.04 * clamp(0, (var(--p,0) - .21) * 12, 1) - 1.04 * clamp(0, (var(--p,0) - .45) * 12, 1)))" })} className="jos-z1">
                      <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "16px 18px 0 #141311,0 36px 74px -28px rgba(13,11,20,.55)", "opacity": "var(--w1,1)", "transform": "scale(calc(.72 + .28 * var(--w1,1)))", "transition": "opacity .3s ease,transform .3s cubic-bezier(.3,0,.6,1)" })}>
                        <div style={s({ "height": "56px", "display": "flex", "alignItems": "center", "gap": "22px", "padding": "0 20px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                          <div onClick={V.close1} style={s({ "width": "14px", "height": "14px", "borderRadius": "999px", "background": "#141311", "cursor": "none", "flex": "none", "transition": "transform .14s" })} className="jhdh7"></div>
                          <span style={s({ "fontSize": "18px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                            {"Experience"}
                          </span>
                          <div style={s({ "display": "flex", "alignItems": "center", "gap": "22px", "marginLeft": "auto" })}>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh8">
                              {"File"}
                            </span>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh9">
                              {"Sort"}
                            </span>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "flexDirection": "column", "gap": "16px", "padding": "20px 36px 8px" })}>
                          <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "14px" })}>
                            <span style={s({ "fontSize": "14px", "fontWeight": "700", "letterSpacing": ".16em", "textTransform": "uppercase", "color": "#141311" })}>
                              {"01"}
                            </span>
                            <span style={s({ "fontSize": "34px", "fontWeight": "700", "letterSpacing": "-.04em", "color": "#141311" })} className="jos-zw">
                              {"Things I started"}
                            </span>
                            <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850" })}>
                              {V.ventureCount}
                            </span>
                          </div>
                          <div style={s({ "display": "flex", "gap": "20px" })}>
                            {(V.ventures ?? []).map((v: any, vIndex: number) => (
                              <Fragment key={vIndex}>
                                <a href={v.href} target="_blank" rel="noreferrer" style={s({ "width": "277px", "flex": "none", "display": "flex", "flexDirection": "column", "gap": "9px", "cursor": "none", "transition": "transform .2s cubic-bezier(.2,.9,.3,1)", "--zd": ".05s" })} className="jos-zr jhdh10">
                                  <div style={s({ "height": "84px", "borderRadius": "14px", "overflow": "hidden", "background": "#e6e1d3", "boxShadow": "6px 7px 0 #141311" })}>
                                    <img src={v.shot} alt={v.name} style={s({ "width": "100%", "height": "100%", "objectFit": "cover", "objectPosition": "50% 8%", "display": "block" })} />
                                  </div>
                                  <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "10px" })}>
                                    <span style={s({ "fontSize": "23px", "fontWeight": "700", "letterSpacing": "-.03em", "color": "#141311" })}>
                                      {v.name}
                                    </span>
                                    <span style={s({ "fontSize": "11px", "fontWeight": "700", "letterSpacing": ".12em", "textTransform": "uppercase", "color": "#12300f", "background": "#7ac274", "borderRadius": "999px", "padding": "4px 9px", "marginLeft": "auto" })}>
                                      {v.status}
                                    </span>
                                  </div>
                                  <span style={s({ "fontSize": "16px", "lineHeight": "1.25", "color": "#3a3630" })}>
                                    {v.tagline}
                                  </span>
                                  <span style={s({ "marginTop": "auto", "fontSize": "13px", "fontWeight": "700", "letterSpacing": ".12em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                                    {v.role}
                                  </span>
                                </a>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "flexDirection": "column", "gap": "12px", "padding": "14px 36px 6px" })}>
                          <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "14px" })}>
                            <span style={s({ "fontSize": "14px", "fontWeight": "700", "letterSpacing": ".16em", "textTransform": "uppercase", "color": "#141311" })}>
                              {"02"}
                            </span>
                            <span style={s({ "fontSize": "26px", "fontWeight": "700", "letterSpacing": "-.03em", "color": "#141311", "--zd": ".12s" })} className="jos-zr">
                              {"Where I work"}
                            </span>
                            <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850" })}>
                              {V.roleCount}
                            </span>
                          </div>
                          <div style={s({ "display": "flex", "flexWrap": "wrap", "gap": "14px 18px" })}>
                            {(V.roles ?? []).map((role: any, roleIndex: number) => (
                              <Fragment key={roleIndex}>
                                <a href={role.url} target="_blank" rel="noreferrer" style={s({ "width": "210px", "flex": "none", "display": "flex", "flexDirection": "column", "gap": "2px", "cursor": "none", "transition": "transform .18s cubic-bezier(.2,.9,.3,1)" })} className="jhdh11">
                                  <div style={s({ "display": "flex", "alignItems": "center", "gap": "8px" })}>
                                    <img src={role.icon} alt="" style={s({ "width": "15px", "height": "15px", "flex": "none", "borderRadius": "4px", "objectFit": "contain", "display": "block" })} />
                                    <span style={s({ "fontSize": "11px", "fontWeight": "700", "letterSpacing": ".13em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                                      {role.year}
                                    </span>
                                  </div>
                                  <span style={s({ "fontSize": "18px", "fontWeight": "700", "letterSpacing": "-.03em", "lineHeight": "1.1", "color": "#141311" })}>
                                    {role.org}
                                  </span>
                                  <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                                    {role.role}
                                  </span>
                                </a>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "20px", "padding": "12px 36px 16px" })}>
                          <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "9px", "flex": "none" })}>
                            <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                              {"03"}
                            </span>
                            <span style={s({ "fontSize": "17px", "fontWeight": "700", "letterSpacing": "-.02em", "color": "#141311", "whiteSpace": "nowrap" })}>
                              {"Sites for other people"}
                            </span>
                          </div>
                          <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "24px", "flex": "1", "minWidth": "0" })}>
                            {(V.webWork ?? []).map((w: any, wIndex: number) => (
                              <Fragment key={wIndex}>
                                <a href={w.href} target="_blank" rel="noreferrer" style={s({ "flex": "1 1 0", "minWidth": "0", "display": "flex", "alignItems": "baseline", "gap": "8px", "cursor": "none", "transition": "transform .16s" })} className="jhdh12">
                                  <span style={s({ "fontSize": "16px", "fontWeight": "700", "color": "#141311", "borderBottom": "2.5px solid #141311", "whiteSpace": "nowrap", "flex": "none" })}>
                                    {w.name}
                                  </span>
                                  <span style={s({ "fontSize": "13px", "lineHeight": "1.3", "color": "#6f6a61", "minWidth": "0" })}>
                                    {w.note}
                                  </span>
                                </a>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "center", "gap": "14px", "padding": "12px 22px", "boxShadow": "inset 0 2.5px 0 #141311" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Click anything to open the live site"}
                          </span>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850", "marginLeft": "auto" })}>
                            {"2 of 4 windows"}
                          </span>
                        </div>
                      </div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "100px", "top": "104px", "width": "1240px", "zIndex": "12", "pointerEvents": "var(--pe2,none)", "transformOrigin": "633px 700px", "opacity": "calc(clamp(0, (var(--p,0) - .46) * 12, 1) - clamp(0, (var(--p,0) - .7) * 12, 1))", "transform": "scale(calc(.04 + 1.04 * clamp(0, (var(--p,0) - .46) * 12, 1) - 1.04 * clamp(0, (var(--p,0) - .7) * 12, 1)))" })} className="jos-z2">
                      <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "16px 18px 0 #141311,0 36px 74px -28px rgba(13,11,20,.55)", "opacity": "var(--w2,1)", "transform": "scale(calc(.72 + .28 * var(--w2,1)))", "transition": "opacity .3s ease,transform .3s cubic-bezier(.3,0,.6,1)" })}>
                        <div style={s({ "height": "56px", "display": "flex", "alignItems": "center", "gap": "22px", "padding": "0 20px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                          <div onClick={V.close2} style={s({ "width": "14px", "height": "14px", "borderRadius": "999px", "background": "#141311", "cursor": "none", "flex": "none", "transition": "transform .14s" })} className="jhdh13"></div>
                          <span style={s({ "fontSize": "18px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                            {"Writing"}
                          </span>
                          <div style={s({ "display": "flex", "alignItems": "center", "gap": "22px", "marginLeft": "auto" })}>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh14">
                              {"File"}
                            </span>
                            <span onClick={V.subscribe} style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh15">
                              {"Subscribe"}
                            </span>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "stretch", "minHeight": "400px" })}>
                          <div style={s({ "flex": "1", "minWidth": "0", "padding": "30px 36px 34px", "display": "flex", "flexDirection": "column", "gap": "18px", "boxShadow": "inset -2.5px 0 0 #141311" })}>
                            <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "12px" })}>
                              <span style={s({ "fontSize": "14px", "fontWeight": "700", "letterSpacing": ".16em", "color": "#141311" })}>
                                {"01"}
                              </span>
                              <span style={s({ "fontSize": "52px", "fontWeight": "700", "letterSpacing": "-.045em", "lineHeight": "1", "color": "#141311" })} className="jos-zw">
                                {"Writing"}
                              </span>
                            </div>
                            <p style={s({ "margin": "0", "maxWidth": "520px", "fontSize": "19px", "lineHeight": "1.5", "color": "#3a3630", "textWrap": "pretty" })}>
                              {" Notes on the things on this page: designing them, building them, and getting them out of the door. It all lives at /writing. "}
                            </p>
                            {V.hasPosts ? (
                              <>
                                <div style={s({ "display": "flex", "flexDirection": "column", "gap": "2px", "boxShadow": "inset 0 2.5px 0 #141311" })}>
                                  {(V.posts ?? []).map((post: any, postIndex: number) => (
                                    <Fragment key={postIndex}>
                                      <a href={`/writing/${post.slug}`} style={s({ "display": "flex", "alignItems": "baseline", "gap": "14px", "padding": "11px 2px 10px", "boxShadow": "inset 0 -2.5px 0 rgba(20,19,17,.14)", "cursor": "none", "transition": "transform .16s cubic-bezier(.2,.9,.3,1)" })} className="jhdh16">
                                        <span style={s({ "fontSize": "12px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61", "flex": "none", "width": "104px" })}>
                                          {post.date}
                                        </span>
                                        <span style={s({ "fontSize": "19px", "fontWeight": "600", "letterSpacing": "-.02em", "color": "#141311" })}>
                                          {post.title}
                                        </span>
                                      </a>
                                    </Fragment>
                                  ))}
                                </div>
                              </>
                            ) : null}
                            <a href="/writing" style={s({ "alignSelf": "flex-start", "display": "flex", "alignItems": "center", "gap": "22px", "background": "#141311", "borderRadius": "22px", "padding": "18px 20px 18px 26px", "cursor": "none", "transition": "transform .18s cubic-bezier(.2,.9,.3,1)" })} className="jhdh17">
                              <span style={s({ "fontSize": "28px", "fontWeight": "700", "letterSpacing": "-.035em", "color": "#f4f1e6" })}>
                                {"Read the writing"}
                              </span>
                              <span style={s({ "width": "42px", "height": "42px", "borderRadius": "999px", "background": "#7ac274", "color": "#12300f", "fontSize": "19px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none" })}>
                                {"→"}
                              </span>
                            </a>
                            <div style={s({ "marginTop": "auto", "display": "flex", "alignItems": "center", "gap": "12px" })}>
                              <div style={s({ "width": "10px", "height": "10px", "borderRadius": "999px", "background": "#7ac274", "flex": "none" })}></div>
                              <span style={s({ "fontSize": "16px", "color": "#3a3630" })}>
                                {V.hasPosts ? (
                                  <>
                                    {"Also available as RSS."}
                                  </>
                                ) : null}
                                {V.noPosts ? (
                                  <>
                                    {"Nothing published yet. Worth a bookmark."}
                                  </>
                                ) : null}
                              </span>
                            </div>
                          </div>
                          <div style={s({ "width": "520px", "flex": "none", "display": "flex", "flexDirection": "column" })}>
                            <div style={s({ "padding": "30px 34px 22px", "display": "flex", "flexDirection": "column", "gap": "14px" })}>
                              <div style={s({ "display": "flex", "alignItems": "baseline", "gap": "12px" })}>
                                <span style={s({ "fontSize": "14px", "fontWeight": "700", "letterSpacing": ".16em", "color": "#141311" })}>
                                  {"02"}
                                </span>
                                <span style={s({ "fontSize": "34px", "fontWeight": "700", "letterSpacing": "-.04em", "color": "#141311", "--zd": ".1s" })} className="jos-zr">
                                  {"Newsletter"}
                                </span>
                              </div>
                              <span style={s({ "fontSize": "18px", "lineHeight": "1.4", "color": "#3a3630" })}>
                                {"One email when something ships. Your address, nothing else."}
                              </span>
                            </div>
                            <div style={s({ "display": "flex", "alignItems": "center", "gap": "18px", "padding": "0 34px", "boxShadow": "inset 0 -2.5px 0 #141311,inset 0 2.5px 0 #141311" })}>
                              <span style={s({ "fontSize": "13px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#5c5850", "width": "62px", "flex": "none" })}>
                                {"Email"}
                              </span>
                              <input ref={V.refSub} onKeyDown={V.onSubKey} onFocus={V.onFieldFocus} onBlur={V.onFieldBlur} type="email" autoComplete="email" placeholder="you@somewhere.com" style={s({ "flex": "1", "minWidth": "0", "border": "none", "background": "transparent", "padding": "20px 0", "fontSize": "22px", "color": "#141311", "outline": "none", "cursor": "text", "caretColor": "#7ac274" })} />
                            </div>
                            <div style={s({ "padding": "22px 34px 0", "display": "flex", "flexDirection": "column", "gap": "14px" })}>
                              <div onClick={V.subscribe} style={s({ "fontSize": "20px", "fontWeight": "700", "background": "#7ac274", "color": "#12300f", "borderRadius": "16px", "padding": "19px", "textAlign": "center", "cursor": "none", "boxShadow": "6px 7px 0 #141311", "transition": "transform .16s" })} className="jhdh18">
                                {V.subLabel}
                              </div>
                              {V.subOk ? (
                                <>
                                  <div style={s({ "display": "flex", "alignItems": "center", "gap": "12px", "background": "#7ac274", "borderRadius": "14px", "padding": "14px 16px" })}>
                                    <span style={s({ "width": "26px", "height": "26px", "borderRadius": "999px", "background": "#141311", "color": "#f4f1e6", "fontSize": "14px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none" })}>
                                      {"✓"}
                                    </span>
                                    <span style={s({ "fontSize": "17px", "fontWeight": "600", "color": "#12300f" })}>
                                      {"You are on the list."}
                                    </span>
                                  </div>
                                </>
                              ) : null}
                              {V.subErr ? (
                                <>
                                  <div style={s({ "display": "flex", "alignItems": "center", "gap": "12px", "background": "#141311", "borderRadius": "14px", "padding": "14px 16px" })}>
                                    <span style={s({ "width": "26px", "height": "26px", "borderRadius": "999px", "background": "#7ac274", "color": "#12300f", "fontSize": "15px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none" })}>
                                      {"!"}
                                    </span>
                                    <span style={s({ "fontSize": "17px", "fontWeight": "600", "color": "#f4f1e6" })}>
                                      {V.subError}
                                    </span>
                                  </div>
                                </>
                              ) : null}
                            </div>
                            <div style={s({ "marginTop": "auto", "padding": "20px 34px 24px", "display": "flex", "alignItems": "center", "gap": "12px" })}>
                              <span style={s({ "fontSize": "15px", "color": "#6f6a61" })}>
                                {"No schedule, no spam, unsubscribe whenever."}
                              </span>
                            </div>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "center", "gap": "14px", "padding": "12px 22px", "boxShadow": "inset 0 2.5px 0 #141311" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Enter to subscribe"}
                          </span>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850", "marginLeft": "auto" })}>
                            {"3 of 4 windows"}
                          </span>
                        </div>
                      </div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "100px", "top": "104px", "width": "1240px", "zIndex": "13", "pointerEvents": "var(--pe3,none)", "transformOrigin": "633px 700px", "opacity": "clamp(0, calc((var(--p,0) - .71) * 12), 1)", "transform": "scale(calc(.04 + 1.06 * clamp(0, (var(--p,0) - .71) * 12, 1)))" })} className="jos-z3">
                      <div style={s({ "borderRadius": "26px", "background": "#f4f1e6", "overflow": "hidden", "boxShadow": "16px 18px 0 #141311,0 36px 74px -28px rgba(13,11,20,.55)", "opacity": "var(--w3,1)", "transform": "scale(calc(.72 + .28 * var(--w3,1)))", "transition": "opacity .3s ease,transform .3s cubic-bezier(.3,0,.6,1)" })}>
                        <div style={s({ "height": "56px", "display": "flex", "alignItems": "center", "gap": "22px", "padding": "0 20px", "boxShadow": "inset 0 -2.5px 0 #141311" })}>
                          <div onClick={V.close3} style={s({ "width": "14px", "height": "14px", "borderRadius": "999px", "background": "#141311", "cursor": "none", "flex": "none", "transition": "transform .14s" })} className="jhdh19"></div>
                          <span style={s({ "fontSize": "18px", "fontWeight": "700", "letterSpacing": "-.015em", "color": "#141311" })}>
                            {"Contact"}
                          </span>
                          <div style={s({ "display": "flex", "alignItems": "center", "gap": "22px", "marginLeft": "auto" })}>
                            <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh20">
                              {"File"}
                            </span>
                            <a href="/design" style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#5c5850", "cursor": "none" })} className="jhdh21">
                              {"Studio"}
                            </a>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "stretch", "minHeight": "330px" })}>
                          <div style={s({ "flex": "1", "minWidth": "0", "padding": "30px 36px 32px", "display": "flex", "flexDirection": "column", "gap": "20px", "boxShadow": "inset -2.5px 0 0 #141311" })}>
                            <span style={s({ "fontSize": "56px", "fontWeight": "700", "letterSpacing": "-.045em", "lineHeight": "1", "color": "#141311" })} className="jos-zw">
                              {"Say hello."}
                            </span>
                            <a href={V.mailto} style={s({ "alignSelf": "flex-start", "display": "flex", "flexDirection": "column", "gap": "4px", "cursor": "none", "transition": "transform .18s cubic-bezier(.2,.9,.3,1)" })} className="jhdh22">
                              <span style={s({ "fontSize": "13px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#6f6a61" })}>
                                {"Email"}
                              </span>
                              <span style={s({ "fontSize": "34px", "fontWeight": "600", "letterSpacing": "-.03em", "color": "#141311", "borderBottom": "3px solid #7ac274" })}>
                                {V.email}
                              </span>
                            </a>
                            <a href={V.cvHref} download={V.cvFilename} style={s({ "alignSelf": "flex-start", "display": "flex", "alignItems": "center", "gap": "22px", "background": "#7ac274", "borderRadius": "22px", "padding": "18px 18px 18px 26px", "boxShadow": "8px 9px 0 #141311", "cursor": "none", "transition": "transform .18s cubic-bezier(.2,.9,.3,1)" })} className="jhdh23">
                              <div style={s({ "display": "flex", "flexDirection": "column", "gap": "2px" })}>
                                <span style={s({ "fontSize": "30px", "fontWeight": "700", "letterSpacing": "-.035em", "lineHeight": "1", "color": "#12300f" })}>
                                  {"Download CV"}
                                </span>
                                <span style={s({ "fontSize": "16px", "fontWeight": "600", "color": "#1d3d1c" })}>
                                  {V.cvFilename}
                                </span>
                              </div>
                              <span style={s({ "width": "48px", "height": "48px", "borderRadius": "999px", "background": "#141311", "color": "#f4f1e6", "fontSize": "22px", "fontWeight": "700", "display": "flex", "alignItems": "center", "justifyContent": "center", "flex": "none" })}>
                                {"↓"}
                              </span>
                            </a>
                            <div style={s({ "marginTop": "auto", "display": "flex", "alignItems": "center", "gap": "12px" })}>
                              <span style={s({ "fontSize": "16px", "color": "#3a3630" })}>
                                {"Client work and studio pricing live on"}
                              </span>
                              <a href="/design" style={s({ "fontSize": "16px", "fontWeight": "700", "color": "#141311", "borderBottom": "2.5px solid #7ac274", "cursor": "none" })}>
                                {"jawadOS, the studio →"}
                              </a>
                            </div>
                          </div>
                          <div style={s({ "width": "470px", "flex": "none", "display": "flex", "flexDirection": "column", "gap": "18px", "padding": "28px 34px 30px" })}>
                            <img src="/design/jawad-cut.webp" alt="Jawad" style={s({ "alignSelf": "center", "width": "190px", "height": "190px", "objectFit": "contain", "animation": "breathe 5.5s ease-in-out infinite" })} />
                            <div style={s({ "display": "flex", "alignItems": "center", "gap": "12px" })}>
                              <span style={s({ "fontSize": "13px", "fontWeight": "700", "letterSpacing": ".14em", "textTransform": "uppercase", "color": "#5c5850" })}>
                                {"Elsewhere"}
                              </span>
                              <div style={s({ "flex": "1", "height": "2.5px", "background": "#141311", "opacity": ".14" })}></div>
                            </div>
                            <div style={s({ "display": "flex", "flexWrap": "wrap", "gap": "10px" })}>
                              {(V.socials ?? []).map((social: any, socialIndex: number) => (
                                <Fragment key={socialIndex}>
                                  <a href={social.href} target="_blank" rel="noreferrer" aria-label={social.label} style={s({ "display": "flex", "alignItems": "center", "gap": "9px", "fontSize": "16px", "fontWeight": "600", "color": "#141311", "padding": "9px 16px 9px 12px", "borderRadius": "999px", "boxShadow": "inset 0 0 0 2.5px #141311", "cursor": "none", "transition": "transform .16s cubic-bezier(.2,.9,.3,1),box-shadow .16s" })} className="jhdh24">
                                    <svg viewBox="0 0 24 24" width="17" height="17" aria-hidden="true" style={s({ "flex": "none", "display": "block" })}>
                                      <path d={social.path} fill={social.brand}></path>
                                    </svg>
                                    {social.label}
                                  </a>
                                </Fragment>
                              ))}
                            </div>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "alignItems": "center", "gap": "14px", "padding": "12px 22px", "boxShadow": "inset 0 2.5px 0 #141311" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Mail goes straight to me"}
                          </span>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850", "marginLeft": "auto" })}>
                            {"4 of 4 windows"}
                          </span>
                        </div>
                      </div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "0", "top": "0", "width": "26px", "height": "30px", "zIndex": "24", "pointerEvents": "none", "opacity": "var(--sprite,1)", "transform": "translate(var(--cx,720px), var(--cy,700px)) scale(var(--press,1))" })}>
                      <div style={s({ "width": "26px", "height": "30px", "background": "#141311", "clipPath": "polygon(0 0,0 78%,26% 58%,46% 100%,66% 88%,46% 46%,80% 44%)" })}></div>
                      <div style={s({ "position": "absolute", "left": "3px", "top": "3px", "width": "19px", "height": "22px", "background": "#f4f1e6", "clipPath": "polygon(0 0,0 74%,28% 54%,48% 96%,62% 86%,42% 42%,72% 40%)" })}></div>
                      <div style={s({ "position": "absolute", "left": "24px", "top": "26px", "fontFamily": "'Space Grotesk',system-ui,sans-serif", "fontSize": "14px", "fontWeight": "600", "background": "#141311", "color": "#f4f1e6", "borderRadius": "999px", "padding": "6px 11px", "whiteSpace": "nowrap", "opacity": "var(--tip,0)" })}>
                        {V.cursorTip}
                      </div>
                    </div>
                    <div style={s({ "position": "absolute", "left": "50%", "bottom": "22px", "transform": "translateX(-50%)", "zIndex": "20", "display": "flex", "alignItems": "flex-end", "gap": "22px", "background": "linear-gradient(180deg,#fbf9f1 0%,#efeadb 100%)", "boxShadow": "9px 10px 0 #141311,inset 0 2px 0 rgba(255,255,255,.9),0 30px 54px -16px rgba(4,3,8,.75),0 60px 90px -30px rgba(4,3,8,.6)", "padding": "16px 22px 14px", "borderRadius": "26px" })}>
                      <div onClick={V.jMe} style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "9px", "cursor": "none" })}>
                        <div style={s({ "position": "relative", "width": "66px", "height": "66px", "borderRadius": "19px", "background": "#fbf9f1", "boxShadow": "5px 6px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transformOrigin": "50% 100%" })} className="jhdh25">
                          <div style={s({ "position": "relative", "width": "34px", "height": "25px", "borderRadius": "6px", "background": "#141311" })}>
                            <div style={s({ "position": "absolute", "left": "9px", "top": "-5px", "width": "13px", "height": "5px", "borderRadius": "3px 3px 0 0", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "left": "10px", "top": "6px", "width": "14px", "height": "14px", "borderRadius": "999px", "background": "#fbf9f1" })}></div>
                            <div style={s({ "position": "absolute", "left": "13px", "top": "9px", "width": "8px", "height": "8px", "borderRadius": "999px", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "right": "4px", "top": "4px", "width": "4px", "height": "4px", "borderRadius": "999px", "background": "#fbf9f1" })}></div>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Me"}
                          </span>
                          <div style={s({ "width": "18px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav0,0)", "transition": "opacity .3s" })}></div>
                        </div>
                      </div>
                      <div onClick={V.jWork} style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "9px", "cursor": "none" })}>
                        <div style={s({ "position": "relative", "width": "66px", "height": "66px", "borderRadius": "19px", "background": "#fbf9f1", "boxShadow": "5px 6px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transformOrigin": "50% 100%" })} className="jhdh26">
                          <div style={s({ "position": "relative", "width": "34px", "height": "27px" })}>
                            <div style={s({ "position": "absolute", "left": "0", "top": "0", "width": "16px", "height": "7px", "borderRadius": "3px 5px 0 0", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "left": "0", "top": "5px", "width": "34px", "height": "22px", "borderRadius": "4px", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "left": "4px", "top": "13px", "width": "26px", "height": "3px", "borderRadius": "2px", "background": "#fbf9f1" })}></div>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Experience"}
                          </span>
                          <div style={s({ "width": "18px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav1,0)", "transition": "opacity .3s" })}></div>
                        </div>
                      </div>
                      <div onClick={V.jWrite} style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "9px", "cursor": "none" })}>
                        <div style={s({ "position": "relative", "width": "66px", "height": "66px", "borderRadius": "19px", "background": "#fbf9f1", "boxShadow": "5px 6px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transformOrigin": "50% 100%" })} className="jhdh27">
                          <div style={s({ "position": "relative", "width": "30px", "height": "30px" })}>
                            <div style={s({ "position": "absolute", "left": "0", "bottom": "0", "width": "30px", "height": "5px", "borderRadius": "2px", "background": "#141311" })}></div>
                            <div style={s({ "position": "absolute", "left": "4px", "bottom": "8px", "width": "20px", "height": "6px", "background": "#141311", "transform": "rotate(-42deg)", "transformOrigin": "left center" })}></div>
                            <div style={s({ "position": "absolute", "left": "22px", "top": "2px", "width": "8px", "height": "8px", "borderRadius": "2px", "background": "#141311" })}></div>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Writing"}
                          </span>
                          <div style={s({ "width": "18px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav2,0)", "transition": "opacity .3s" })}></div>
                        </div>
                      </div>
                      <div onClick={V.jMail} style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "9px", "cursor": "none", "position": "relative" })}>
                        <div style={s({ "position": "relative", "width": "66px", "height": "66px", "borderRadius": "19px", "background": "#fbf9f1", "boxShadow": "5px 6px 0 #141311", "display": "flex", "alignItems": "center", "justifyContent": "center", "transformOrigin": "50% 100%" })} className="jos-pulse jhdh28">
                          <div style={s({ "position": "relative", "width": "34px", "height": "24px", "borderRadius": "4px", "background": "#141311", "overflow": "hidden" })}>
                            <div style={s({ "position": "absolute", "left": "2px", "top": "1px", "width": "30px", "height": "15px", "background": "#fbf9f1", "clipPath": "polygon(0 0,100% 0,50% 100%)" })}></div>
                          </div>
                        </div>
                        <div style={s({ "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px" })}>
                          <span style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#5c5850" })}>
                            {"Contact"}
                          </span>
                          <div style={s({ "width": "18px", "height": "4px", "borderRadius": "2px", "background": "#141311", "opacity": "var(--nav3,0)", "transition": "opacity .3s" })}></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "top": "0", "height": "52px", "background": "linear-gradient(180deg,#211e1a 0%,#151412 58%,#0d0c0a 100%)", "zIndex": "22", "display": "flex", "alignItems": "center", "justifyContent": "space-between", "padding": "0 20px", "boxShadow": "inset 0 1.5px 0 rgba(244,241,230,.1),inset 0 -1px 0 rgba(0,0,0,.9),0 16px 30px -12px rgba(0,0,0,.85)" })}>
                    <div style={s({ "display": "flex", "alignItems": "center", "gap": "4px" })}>
                      <div onClick={V.jTop} style={s({ "display": "flex", "alignItems": "center", "gap": "10px", "cursor": "none", "marginRight": "10px", "padding": "6px 13px 6px 6px", "borderRadius": "999px", "transition": "background .18s" })} className="jhdh29">
                        <div style={s({ "width": "13px", "height": "13px", "background": "#7ac274", "borderRadius": "3px", "transform": "rotate(45deg)", "boxShadow": "0 0 14px rgba(122,194,116,.75)" })}></div>
                        <span style={s({ "fontSize": "16px", "fontWeight": "700", "letterSpacing": "-.01em", "color": "#f4f1e6" })}>
                          {"jawadOS"}
                        </span>
                      </div>
                      <span onClick={V.jMe} style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#f4f1e6", "padding": "7px 14px", "borderRadius": "999px", "cursor": "none", "opacity": "calc(.5 + .5 * var(--nav0,0))", "background": "rgba(244,241,230,calc(var(--nav0,0) * .14))", "boxShadow": "inset 0 0 0 1.5px rgba(244,241,230,calc(var(--nav0,0) * .16))", "transition": "opacity .28s,background .28s,box-shadow .28s" })} className="jhdh30">
                        {"Me"}
                      </span>
                      <span onClick={V.jWork} style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#f4f1e6", "padding": "7px 14px", "borderRadius": "999px", "cursor": "none", "opacity": "calc(.5 + .5 * var(--nav1,0))", "background": "rgba(244,241,230,calc(var(--nav1,0) * .14))", "boxShadow": "inset 0 0 0 1.5px rgba(244,241,230,calc(var(--nav1,0) * .16))", "transition": "opacity .28s,background .28s,box-shadow .28s" })} className="jhdh31">
                        {"Experience"}
                      </span>
                      <span onClick={V.jWrite} style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#f4f1e6", "padding": "7px 14px", "borderRadius": "999px", "cursor": "none", "opacity": "calc(.5 + .5 * var(--nav2,0))", "background": "rgba(244,241,230,calc(var(--nav2,0) * .14))", "boxShadow": "inset 0 0 0 1.5px rgba(244,241,230,calc(var(--nav2,0) * .16))", "transition": "opacity .28s,background .28s,box-shadow .28s" })} className="jhdh32">
                        {"Writing"}
                      </span>
                      <span onClick={V.jMail} style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#f4f1e6", "padding": "7px 14px", "borderRadius": "999px", "cursor": "none", "opacity": "calc(.5 + .5 * var(--nav3,0))", "background": "rgba(244,241,230,calc(var(--nav3,0) * .14))", "boxShadow": "inset 0 0 0 1.5px rgba(244,241,230,calc(var(--nav3,0) * .16))", "transition": "opacity .28s,background .28s,box-shadow .28s" })} className="jhdh33">
                        {"Contact"}
                      </span>
                    </div>
                    <div style={s({ "display": "flex", "alignItems": "center", "gap": "12px" })}>
                      <span onClick={V.toggleSound} style={s({ "fontSize": "14px", "fontWeight": "600", "color": "#8d887d", "padding": "7px 13px", "borderRadius": "999px", "cursor": "none", "transition": "color .18s,background .18s" })} className="jhdh34">
                        {V.soundLabel}
                      </span>
                      <span style={s({ "fontSize": "15px", "fontWeight": "600", "color": "#8d887d", "fontVariantNumeric": "tabular-nums", "paddingRight": "4px" })}>
                        {V.clock}
                      </span>
                      <a href="/design" style={s({ "fontSize": "15px", "fontWeight": "700", "background": "#7ac274", "color": "#12300f", "borderRadius": "999px", "padding": "8px 17px", "cursor": "none", "boxShadow": "0 3px 0 #4b8546,0 10px 20px -6px rgba(122,194,116,.6)", "transition": "transform .16s,box-shadow .16s" })} className="jhdh35">
                        {"The studio"}
                      </a>
                    </div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "50%", "top": "0", "transform": "translateX(-50%)", "width": "212px", "height": "36px", "background": "#141311", "borderRadius": "0 0 14px 14px", "zIndex": "24", "display": "flex", "alignItems": "center", "justifyContent": "center", "gap": "7px" })}>
                    <div style={s({ "width": "8px", "height": "8px", "borderRadius": "50%", "background": "#242220" })}></div>
                    <div style={s({ "width": "4px", "height": "4px", "borderRadius": "50%", "background": "#2e2b28" })}></div>
                  </div>
                  <div style={s({ "position": "absolute", "left": "0", "right": "0", "top": "0", "height": "340px", "background": "linear-gradient(160deg,rgba(255,255,255,.16) 0%,rgba(255,255,255,.05) 42%,transparent 60%)", "pointerEvents": "none", "zIndex": "26" })}></div>
                  <div style={s({ "position": "absolute", "inset": "0", "zIndex": "27", "pointerEvents": "none", "background": "radial-gradient(132% 112% at 50% 48%,rgba(0,0,0,0) 58%,rgba(0,0,0,.28) 100%)" })}></div>
                  <div style={s({ "position": "absolute", "inset": "0", "zIndex": "28", "pointerEvents": "none", "opacity": ".05", "background": "repeating-linear-gradient(0deg,rgba(0,0,0,.55) 0 1px,transparent 1px 3px)" })}></div>
                </div>
              </div>
            </div>
          </div>
          <div style={s({ "position": "absolute", "inset": "0", "pointerEvents": "none", "background": "radial-gradient(82% 74% at 50% 46%,rgba(0,0,0,0) 42%,rgba(0,0,0,.5) 82%,rgba(0,0,0,.72) 100%)" })}></div>
        </div>
      </div>
    </>
  );
}
